### ISSUE TITLE
Project 1 Proposal: Symbolic Verification Backend for Translation Validation

### ISSUE THREAD

**Issue by rachitnigam** [sampsyo/cs6120#10]
Team: @rachitnigam and @sgpthomas

**What will you do?**
We'll write a pass that compiles _basic blocks_ in bril programs to SMT formulas using [Rosette](https://emina.github.io/rosette/). As a stretch goal, we'll try to do this for full brill programs.

**How will you do it?**
Three steps:
- Parse Bril using Racket
- Write an interpreter for Bril programs in Rosette
- Verify!!

**How will you empirically measure success?**
We'll verify the correctness of a local and a global DCE pass. It is possible that verification will not scale to global optimizations/large programs so we'll try different encodings for the programs.

**Comment by sampsyo** [comment]
Awesome! I like the idea of sticking to basic blocks at first. I assume that all the "live-ins" to a given basic block (i.e., anything read by any instruction) will be treated as symbolic, right? And all variables assigned to by any instruction will be the targets for verification? (Or else you could just verify `print`-equivalence instead, but that's somewhat less satisfying for a local analysis.)
