### ISSUE TITLE
Project 3 Proposal: Loop perforation

### ISSUE THREAD

**Issue by gyauney** [sampsyo/cs6120#100]
**What will you do?**
We will implement a minimal version of [loop perforation][], as well as other simple approximate computing techniques. 

[loop perforation]: https://people.csail.mit.edu/rinard/paper/fse11.pdf

**How will you do it?**
We are going to implement an LLVM pass for loop perforation. We can use existing LLVM machinery to identify and canonicalize loops (`loops` and `loop-simplify`, respectively). We will reject possible perforations that crash.

Beyond simple perforation, we'd also like to experiment with other approximation techniques such as copying values from one iteration to adjacent skipped iterations (leading to output that has inaccurate instead of uninitialized values).

**How will you empirically measure success?**
Like the paper, we will test on the [PARSEC][] benchmark suite. We'll also use existing image filter benchmarks from the approximate computing literature (which will lead to a more colorful blog post!).

[PARSEC]: https://parsec.cs.princeton.edu/

**Team members:**
@avanhatt, @orichardson

**Comment by sampsyo** [comment]
Sounds great! Just for fun, here's a [somewhat silly paper about extending loop perforation to only skip parts of loops](https://www.semanticscholar.org/paper/Sculptor%3A-Flexible-Approximation-with-Selective-Li-Park/d0138b943d1d69bf34f9e5f517d2792372a93cbf).

**Comment by sampsyo** [comment]
Closed by #127.
