### ISSUE TITLE
Project 3 Proposal: Strength Reduction

### ISSUE THREAD

**Issue by xu3kev** [sampsyo/cs6120#101]
**What will you do?**
We will implement strength reduction, or more specifically, numerical strength reduction. For example, we will try to replace two to the power constant integer multiplication with shift operator. 

**How will you do it?**
First, we will build a table of instruction patterns that can be replaced by a more efficient one. For example, `x*2` can be replaced by `x<<1`. Then, in our custom LLVM pass, we will identify those instructions in the program that matches those pattern and replace that instruction with more efficient instructions.
A problem I see now is that the kind of instructions pattern we can replace with a more efficient one is limited. For example, in modern intel CPU, the latency and throughput of `MUL` and `ADD` are the same, this prevent us from replacing `x * 3` with `(x << 1) + x`.  

**How will you empirically measure success?**
We first will evaluate our optimization pass on some common benchmark suite. In addition, we will also implement some algorithms from number theory or cryptography that heavily utilize integer arithmetics. We expect that we would see more improvement in these algorithms.

**Team members:**
@0x486F626F 
(Update: added member)

**Comment by sampsyo** [comment]
Sounds good overall! To be clear, I think a "standard benchmark suite" should be fine for this. No need to worry about crafting your own crypto benchmarks. Which suite will you use—PARSEC, perhaps? I think there should be plenty of interesting integer ops in that suite.

Will you be working alone? So "we" in the first sentence is "the royal we"?

**Comment by 0x486F626F** [comment]
I will work with Wending on this project.
One thing I would add is that we can have a cost module on each instructions, like number of cycles for each instruction. With this information, it can determine whether to optimize some expressions or not. And we can also calculate "theoretical" number of cycles we can save on the strength reduction.

**Comment by sampsyo** [comment]
Resolved in #133.
