### ISSUE TITLE
Project 3 Proposal: Autovectorization

### ISSUE THREAD

**Issue by hackedy** [sampsyo/cs6120#102]
**What will you do?**
We are going to implement a simple autovectorization pass for LLVM targeting tensor computations produced by [taco](http://tensor-compiler.org).

**How will you do it?**
Taco compiles "tensor expressions" like `y(i) = A(i,j) * x(j)` to efficient C code. We'll pass that C to clang to produce LLVM IR. Our LLVM pass will autovectorize the loops in the generated IR.

**How will you empirically measure success?**
We'll use the existing [taco-bench](https://github.com/tensor-compiler/taco-bench) benchmark suite as a framework for our evaluation. For each tensor expression in the benchmark suite, we'll compare the runtime of:

- Taco's unvectorized code
- our autovectorized code
- the hand-written kernels available in Intel's MKL

Fortunately there is already code in taco-bench for comparing to MKL and several other numerical libraries.

**Team members:**
@g-c-c @rolph-recto

**Comment by sampsyo** [comment]
Yaaay; this should be awesome! Looking forward to it.
