### ISSUE TITLE
Project 3 Proposal: Strength Reduction

### ISSUE THREAD

**Issue by zhouyuan1119** [sampsyo/cs6120#106]
**What will you do?**
We will implement the loop strength reduction algorithm described in [the lecture slides from Prof. Pingali](http://www.cs.utexas.edu/~pingali/CS380C/2019/lectures/strengthReduction.pdf). The described algorithm seems to be a simplified version of the [OSR algorithm](https://dl.acm.org/citation.cfm?id=504709.504710&coll=DL&dl=GUIDE) proposed by Cooper et al. One typical use case of this technique is to replace multiplications that arise from computing array indices in loops with additions. 

**How will you do it?**
Both the slides and the paper describes the algorithm with a lot of details, although in pretty different manners. We need to write functions to (1) find induction variables, (2) replace all the multiplications in non-basic induction variables with additions, and (3) initialize the replaced induction variables in the loop preheader. The IR program generated by LLVM is already in SSA form. LLVM also provides a set of other passes that can simplify our pass, such as loop simplification and constant propagation. Dead code elimination and constant propagation should be run to clean up the code after our loop strength reduction pass. 

**How will you empirically measure success?**
We will write simple test programs to verify the correctness of our implementation. After that, we will use the [Embench benchmark suite](https://www.embench.org) to further test the robustness of our implementation and measure speedup. 

**Team members:**
@Hecmay @seanlatias @zhouyuan1119

**Comment by sampsyo** [comment]
Sounds excellent! This should be of medium difficulty, I think, so be sure to get started early. :smiley: Good luck!

**Comment by sampsyo** [comment]
Closed by #130.
