### ISSUE TITLE
Project 3 Proposal: Dynamic edge profiling with optimal counter placement

### ISSUE THREAD

**Issue by liuhenry4428** [sampsyo/cs6120#109]
**What will you do?**
We plan to implement dynamic edge profiling. Our implementation will differ from Neil, Elaine, and Zhijing's implementation in that we plan to use the optimal (fewest) number of counters without losing profiling information

**How will you do it?**
We plan to use Knuth's algorithm. See section 2.4 of [this LLVM document](https://llvm.org/pubs/2010-04-NeustifterProfiling.pdf)

**How will you empirically measure success?**
We will first test manually by controlling the number of times an edge is traversed. Then, we will leverage existing optimizations to measure whether the profiled counters decrease after an optimization is applied. 

**Team members:**
@kavoor  @liuhenry4428

**Comment by sampsyo** [comment]
Sounds good! To clarify, about your evaluation: sounds like you'll compare some subset these treatments:

- Original program, with some optimizations, like `-O2` or whatever
- The optimized program with your profiling inserted
- The optimized program with your profiling inserted, and then *re-optimized again* with `-O2` or whatever

Is that right? In particular, I don't think you need to do a comparison with `-O0` unoptimized code.

**Comment by liuhenry4428** [comment]
Yes, that's right  😀
