### ISSUE TITLE
Project 1 Proposal: Compiling Bril IR into LLVM 

### ISSUE THREAD

**Issue by Hecmay** [sampsyo/cs6120#11]
**What will you do?**
Compiling Bril IR into LLVM 

**How will you do it?**
Write a parser in C and use LLVM IRBuilder to build the JIT compilation flow. Our system should be flexible enough to support future features such as floating points and other arithmetic operations.

**How will you empirically measure success?**
Develop some test cases. Run through the LLVM and assert final results are the same with Typescript.

**Team members**
@seanlatias
@zhouyuan1119
@Hecmay

**Comment by sampsyo** [comment]
Cool! Using IRBuilder does seem like a good way to go about it. See also #4 and #6, where there are other people also interested in generating LLVM. I provided some advice about how to approach it there. And you might consider coordinating with other people trying to things along similar lines.

> Write a parser in C

Please don't bother writing your own parser. You can use an off-the-shelf JSON parser to load in Bril programs. In fact, [LLVM has one built in](http://llvm.org/doxygen/JSON_8h.html)!
