### ISSUE TITLE
Project 3 Proposal: Implement Path profiling

### ISSUE THREAD

**Issue by Dan12** [sampsyo/cs6120#110]
**What will you do?**

I will implement path profiling in a similar manner to the [Efficient Path Profiling](https://dl.acm.org/citation.cfm?id=243857) paper.

**How will you do it?**

I will initially implement path profiling as an intra-procedural path profiler. I will analyze a function to determine all paths through it and use the algorithm described in the paper to determine which edges need to include profiling instructions. I will then create a global array at program initialization to store all of the path counts for each function. When the program exits, I will save this array to a file and may do some post processing on it to create a decent visual representation. I don't currently have a good way to deal with multithreaded programs accessing this shared array other than locking it on every update. Perhaps more fine grain locking can speed this up but this profiling method may incur a very large overhead.

**How will you empirically measure success?**

First, I will evaluate correctness on a few simple and small test programs. Then, using the [parsec](https://parsec.cs.princeton.edu/index.htm) benchmark suite, I will run the profiler to determine the overhead of the profiler and collect statistics about how many different paths were profiled.

**Team members:**
Just me

**Comment by sampsyo** [comment]
Sounds great! FWIW, the easy thing to do for multithreaded programs might be to use "thread-local" metadata, i.e., one array per thread. Then you don't need to synchronize. You can just add the values together after the program excites.
