### ISSUE TITLE
Project 3 Proposal: Function Inlining

### ISSUE THREAD

**Issue by anastos** [sampsyo/cs6120#112]
**What will you do?**
We will write an LLVM pass to inline small functions.

**How will you do it?**
Whenever we encounter a function call, if that function is small (i.e., less than some number of instructions), then we will replace the call with the body of that function. We may need to do an initial pass to collect all function declarations.

**How will you empirically measure success?**
We will run our optimization on benchmarks from PARSEC. We will also test various function size limits to observe the effects on program performance. Specifically, we will measure: program execution time, memory usage, and code size.

**Team members:**
@Blue9

**Comment by sampsyo** [comment]
Excellent! Sounds great to me. Good luck.

**Comment by sampsyo** [comment]
Closed by #158.
