### ISSUE TITLE
Project 3 Proposal: Dynamic Memory Safety

### ISSUE THREAD

**Issue by dz333** [sampsyo/cs6120#114]
**What will you do?**
Instrument `getelementptr` instructions with guards to ensure that the sized type accesses are safe. If the guard fails, the program will abort with an exception. This is mostly equivalent to array bounds checking for arrays of statically-known size.

**How will you do it?**
I will use the LLVM type information from arrays and structs of statically known size to determine the maximum appropriate offsets for each of the arguments to `getelementptr`
If the offset arguments are constants I can throw a compile time error; otherwise I will insert a guard to check that the offset arguments are of correct size (i.e. between 0 and the maximum index, inclusively). For any pointer whose element length type is unsized (e.g., `i32*` or `[0 x i32]`) I will assume that it points to a single value.

This approach is (mostly) sound but not complete (with respect to `getelementptr`). I say mostly sound because the only sound approach here is to either collect a lot more information about the allocation site for unsized pointers or to disallow all unsized pointers. In general this also requires a pointer liveness analysis for soundness (i.e., even if a pointer is of sized type it may be aliased by another reference which has already been `freed`).  It is also unsound since LLVM allows for bitcasting, which can convert a sized pointer -> unsized -> incorrect size.

Furthermore, it is incomplete because I assume that "unsized" pointers point to element arrays of length 1. Therefore it may be safe to access with an offset of 2 but the guard will fail.

I will attempt to improve the completeness problem within a function by tracking `alloca` calls and calls to `malloc`. In some cases I can use this to determine the runtime size of the allocation and therefore insert a guard using the appropriate maximum index length. LLVM does have some metadata tags which can be used for exactly tracking this information ([dereferencable](https://llvm.org/docs/LangRef.html#dereferenceable-metadata)).

**How will you empirically measure success?**
I will evaluate using the [parsec](https://parsec.cs.princeton.edu/) benchmark suite and my primary evaluation will be on 1) the completeness of the analysis and 2) the overhead of runtime checking. I will evaluate the former by measuring how much I needed to rewrite the benchmark programs in order for them to complete successfully when running approximate safety guards.
**Team members:**
me

**Comment by sampsyo** [comment]
Excellent! This sounds great to me.

For what it's worth, I wouldn't spend _too_ much time trying to fix the PARSEC programs so they don't trigger false positives. You might instead opt to just log all the possible memory safety violations (rather than crashing on the first one) and just report the counts.

**Comment by sampsyo** [comment]
Closed by #126.
