### ISSUE TITLE
Project 3 Proposal: Dynamic Null Checks

### ISSUE THREAD

**Issue by chrisroman** [sampsyo/cs6120#116]
**What will you do?**
I will be adding dynamic checks, specifically adding null checks for every dereference. However, there may be times where we know statically that a pointer is non-null, in which case this runtime null-check would be wasteful. Thus, I will try to do some simple analysis that can determine if a pointer is null.

**How will you do it?**
For adding the null checks, I will go through every instruction that tries to dereference a pointer and add a guard around it, which will cause the program to abort and report where the offending dereference is. For the static null check analysis, I will go for soundness rather than completion. That is, I will only remove the null check if we are guaranteed that the pointer is non-null. 

**How will you empirically measure success?**
I haven't found a suite of tests that accounts for the various ways in which a null pointer could be dereferenced, so for now I'm only relying on hand-written tests. Based on #107 and #111 [BugBench](http://pages.cs.wisc.edu/~shanlu/paper/63-lu.pdf) is a possibility since it has some tests for null pointer dereferences, but I also don't know where to find the tests.

With these tests I can make sure that when a null pointer is dereferenced, we actually catch it before bad things happen like segfaulting. For testing that pointers are guaranteed to be non-null, I can use [CppCheck](http://cppcheck.sourceforge.net/) which produces a warning if there is a potential dereference of a null pointer. So, I will make sure that if my LLVM pass doesn't add a null check around a dereference, CppCheck must not produce a warning about this. This will likely be implemented as some intraprocedural dataflow analysis.

**Team members:**
Just me

**Comment by sampsyo** [comment]
Sounds good! Two things to keep in mind:

- You didn't mention it, but you'll want to measure the performance impact of your null checks. (How much slower do "real" programs go when you've added all these checks?)
- I don't think you have to worry about systematically testing every possibly null-check removal, but if you do, you might find the [Clang static analyzer](https://clang-analyzer.llvm.org) more modern and easier to use than CppCheck.
