### ISSUE TITLE
Project 1 Proposal: A backend translates Bril into Java bytecode

### ISSUE THREAD

**Issue by Neroysq** [sampsyo/cs6120#12]
**What will you do?**
I'll build a backend that translates Bril into Java bytecode.

**How will you do it?**
Possibly write it in Java. Seems straightforward to me. One class, (currently) one function, variables are "local variables" in JVM, and types are already supported in Java bytecode.

**How will you empirically measure success?**
Write examples and check with the reference interpreter for correctness. Also, do some speed tests.

**Comment by sampsyo** [comment]
Sounds good! Do you think you'll emit strings of human-readable Java assembly and then feed it through an assembler, or use something like [ASM](https://asm.ow2.io) to generate bytecode directly? (If the former, there's no need to write it in Java. :smiley:)

**Comment by Neroysq** [comment]
@sampsyo I was thinking of generating Java bytecode, using existing optimization tools and compare the performance, so maybe it's a good fit to use Java. But it is definitely not necessary. Any preference? :smile:

**Comment by sampsyo** [comment]
Sounds good, but to be clear: you can either generate strings (which would require a separate special assembler step to run, but no special library to generate) or in-memory bytes (which probably requires a third-party Java library to generate, but does not need an assembler). Do you know which tools you’ll use?

**Comment by Neroysq** [comment]
@sampsyo I'll generate strings first for sure. Am still investigating the "real" bytecode generation part. I think I'll try to implement a straightforward translation and also use some third-party library like ASM, and compare the performance.

**Comment by sampsyo** [comment]
OK! But I guess the point I was making is that the choice really does deeply influence what you do:

- Text: you can use any programming language.
- "Real" bytecode: you almost certainly need to use a JVM language, and you really want to use an off-the-shelf library like ASM.

I don't think you need to do a direct comparison for this project to be satisfying and cool, FWIW. Just think carefully about what will be the most fun to implement.
