### ISSUE TITLE
Project 1 Proposal: Type Inference for Bril

### ISSUE THREAD

**Issue by chrisroman** [sampsyo/cs6120#13]
**What will you do?**
I will create a type inference system for Bril. Specifically, you should be able
to take a Bril program that specifies only some or none of the types on the
variables and produces a new Bril program that has all the type annotations
(or throws an error).
For example, one will be able to write this bril program:
```
main {
  v0 = const 1;
  v1 = const 2;
  v2 = add v0 v1;
  print v2;
}
```
and transform it into this bril program:
```
main {
  v0: int = const 1;
  v1: int = const 2;
  v2: int = add v0 v1;
  print v2;
}
```

This is useful in cases where the frontend isn't typed. For example, someone
building a Python frontend would need to specify the types of variables, which
may be annoying. This takes some burden off the frontend implementation.
From this, we should get typechecking for free.

**How will you do it?**
First I'll ignore all existing types to the program, and use the language reference
to determine which operations determine the types of each variable. Then for free
type checking, I will run a pass over the original program and make sure the types
we've inferred match what was already given.
I will also change the grammar for `bril2txt` to allow for optional typing on
variables for bril programs.

**How will you empirically measure success?**
First I will take the existing bril programs, remove the type annotations, and
run my type inference program. I will make sure that the output matches the
existing bril programs to verify correctness. Then I will hand curate some
bril programs that shouldn't type check and verify that they don't. I'll also
write bril programs that only explicitly type some variables to make sure the
type inferrer can handle these cases.

**Comment by sampsyo** [comment]
Sounds great! In the JSON AST, I assume that inferred types will just be presented by a missing `type` field on the instruction object?

See also #3, where a group wants to write a normal type checker. You might consider exchanging ideas.

**Comment by chrisroman** [comment]
Yup that's right!

And thanks for the heads up, I'll perhaps check in with them.
