### ISSUE TITLE
Project 1 Proposal: Function calls

### ISSUE THREAD

**Issue by avanhatt** [sampsyo/cs6120#14]
**Team**
@avanhatt @gyauney

**What will you do?**
We will implement function calls, including recursive calls, in BRIL.

**How will you do it?**
First, we will add a `call` instruction to the surface-level syntax. We'll implement the calls using stack frames.

**How will you empirically measure success?**
We'd like to focus the effort of this project on robust empirical validation using an automated testing tool, e.g., [QuickCheck](http://hackage.haskell.org/package/QuickCheck). We'll also handcraft small illustrative examples to be tested with [Turnt](https://github.com/cucapra/turnt), a check-expect style testing tool.

**Comment by sampsyo** [comment]
Sounds good! I recommend y’all coordinate with the group in #8. I also left some random advice about what to do with `main`’s arguments in that thread.
