### ISSUE TITLE
Project 4 Proposal: Data flow graph coverings

### ISSUE THREAD

**Issue by gyauney** [sampsyo/cs6120#141]
**What will you do?**
We will find snippet coverings of data flow graphs (DFGs). That is, given a program's DFG we want to find subgraphs ("snippets") that share structure (up to some definition of snippet equivalence and cost model).

**How will you do it?**
We will be working on programs in LLVM IR because it is an in-memory representation of a DFG.

1. As a first step, we will use a fixed, manually crafted set of small template snippets. The problem formulation then becomes: given the set of snippets and an input program, find the components of the program (at the IR level) that match some snippet. If snippets overlap, we can only chose one.

2. Then, the more interesting step is to generate snippets from the source program. Given a source program and some bounds (how many snippets or nodes per snippet, for example), what snippets successfully cover the most code? We will analyze the performance of this with variants on a greedy algorithm that takes the "best" snippet, for various components of "best." Some ideas for finding snippets:
	- A fixed sampling of code snippets generated from some training set
	- Naive sampling of subgraphs from the source program itself
 	- Variance-maximizing sampling: every time you select a sample, down-weight future samples by similarity to the newly selected one.

3. We will also explore alternate cost-models for mapping one DFG onto another.

4. We will also explore abstracting components of DFGs. More precisely: for each subgraph, we will evaluate the effect of collapsing connected components on the cost of matching with snippets.

**How will you empirically measure success?**
Using LLVM allows us to use a large amount of existing benchmarks and applications. We may also evaluate on randomly-generated DFGs.

We plan to use the following single-program metrics: 
1. Static code coverage: the fraction of a program's code that can be assigned to a snippet (at the IR-instruction level).
2. Dynamic code coverage: the fraction of instructions from an execution on a fixed input that are assigned to a snippet (to capture whether we successfully find snippets in looping structures).
2. For each subgraph size (from one vertex up to the number of vertices in the DFG), the fraction of possible subgraphs snippets that are found in the DFG.

As a first step, we'll evaluate these metrics on small benchmarks (such as selected PARSEC benchmarks, or emBench). For a stretch goal, we'd also like to try running on a larger application (for example, maybe even some of LLVM itself!).

**Team members:**
@orichardson @avanhatt

**Comment by sampsyo** [comment]
Yay; this sounds great! I'm looking forward to it.
