### ISSUE TITLE
Project 4 Proposal: ML based phases ordering with LLVM

### ISSUE THREAD

**Issue by q-hwang** [sampsyo/cs6120#144]
**What will you do?**
We want to continue our P2 exploration in phase reordering on C++, using LLVM optimization passes and better profiling frameworks.

**How will you do it?**

The first stage of our project again would be selecting a subset of available optimizations in LLVM and do extreme analysis, i.e. see how much run time performance change by using different sequence passes. We can then select a reasonable maximum limit for number of passes based on this. For the second stage, we will follow the paper  [Predictive modeling methodology for compiler phase-ordering](https://dl.acm.org/citation.cfm?doid=2872421.2872424) for phase ordering modeling. We will use open source libraries such as [likwid-perfctr](https://github.com/RRZE-HPC/likwid) for program profiling to obtain better features for the program.

**How will you empirically measure success?**

We will evaluate the run time performance of our passes selection versus random order and common heuristic order on benchmarks such as PARSEC.  

**Team members:**
@Chillee

**Comment by sampsyo** [comment]
Sounds pretty cool! I assume the evaluation will compare the same set of LLVM passes as -O2 or whatever but executed in a different order?

**Comment by q-hwang** [comment]
Yeah but the sequence will also include repetition so it is not strictly an "order" in the sense of permutation. So we will limit the maximum number of passes allowed to run (same or smaller than -O2) plus choosing from same set of optimizations flags as -O2, and see if one can still get similar/better performance.

**Comment by sampsyo** [comment]
Sounds cool! The "equal number of passes" restriction seems important… but perhaps an even better point of comparison would measure the trade-off between the actual wall-clock time required to optimize and the efficiency of the code. You could consider drawing a 2D scatter plot with optimization time on the x-axis and execution time on the y-axis to give a picture of the entire trade-off space.
