### ISSUE TITLE
Project 4 Proposal: Code Generation for Polynomial Multiplication

### ISSUE THREAD

**Issue by xu3kev** [sampsyo/cs6120#149]
**What will you do?**
Polynomial multiplication over finite field is widely used in many cryptography schemes. In many of these systems, polynomial multiplication is the bottleneck and they tried to implement it on their own. It makes it hard to compare the performance of different cryptosystems with different schemes because sometimes the result depends on whether they invest enough time to craft their optimized polynomial multiplication. I hope I can design a code generation system to generate high-performance polynomial multiplication to address this problem. 

**How will you do it?**
I am thinking of a way to represent different kinds of polynomial multiplication algorithm. For example, for a polynomial of small degree 768, we can use Karatsuba to divide them to size of 384, then use Toom-3 to 3 way divide to 128 and so on. Maybe a dsl can be useful. I then need to implement a code generator to generate the C program from it. With this, we can then define a search space and search for the fastest program on a given architecture by running all of them.

**How will you empirically measure success?**
I will generate the program and compared the running time of them to handwritten one and state of the art in the cryptosystems.

**Team members:**

**Comment by sampsyo** [comment]
Sounds interesting! Your proposal is not very detailed on how you expect to get good performance—are there standard tricks that a compiler should play?

Also, where will you get your benchmarks from? How many benchmarks do you think you can have for a project like this? And will you obtain open-source C implementations, or will you need to write them yourself?
