### ISSUE TITLE
Project 1 Proposal: Rewrite it (the interpreter) in Rust

### ISSUE THREAD

**Issue by wbthomason** [sampsyo/cs6120#15]
**What will you do?**
Write a (hopefully) faster, (maybe) more featureful Bril interpreter.

**How will you do it?**
Use a systems language, specifically Rust, for baseline speedup. If there's time, I additionally plan to explore interpreter optimization tricks (e.g. https://github.com/status-im/nimbus/wiki/Interpreter-optimization-resources) and/or incorporate language features being added by other Project 1s.

**How will you empirically measure success?**
I'll test correctness vs. the reference interpreter and measure speedup on a set of test programs.

**Note:** I'm open to working with anyone also interested in this, with the caveat that I won't personally be able to do much until after 9/15 due to a paper deadline.

**Comment by sampsyo** [comment]
Great! And nice find with that interpreter optimization page!
