### ISSUE TITLE
Project 4 Proposal: JIT for Bril with OSR

### ISSUE THREAD

**Issue by splashofcrimson** [sampsyo/cs6120#150]
**What will you do?**
For this project, we will build a JIT compiler with on-stack replacement for Bril. We will write extensive benchmark suites to evaluate the performance of the JIT itself as well as the JIT with OSR.

**How will you do it?**
To implement the JIT (without OSR), we will first write code to compile each instruction to x86-64 assembly. Then, whenever an instruction is called from the interpreter, we will compile and run the assembly code. Next, we will implement OSR by using a heuristic to decide when to swap from interpreted to compiled code (perhaps based on functions/instructions that are hot). Some relevant papers we will use to guide our design: ["On-Stack Replacement, Distilled"](http://season-lab.github.io/papers/osr-distilled-pldi18.pdf), ["CS 7600 Survey Paper: On-Stack Replacement"](http://prl.ccs.neu.edu/img/cs7600-mhyee-survey-paper-osr.pdf).

**How will you empirically measure success?**
We will measure our success by writing a fleshed out benchmark suite for Bril and evaluating performance differences between the base interpreter, JIT, and JIT + OSR. We will focus on the wall clock execution time of programs.

**Team members:**
@Blue9 @sameerlal @anastos @splashofcrimson

**Comment by sampsyo** [comment]
Yay! This sounds awesome!

One thing to think about now is how you will generate machine code. Presumably you won't write an assembler yourself. :smiley: Some options include:

- LLVM
- [Cranelift](https://github.com/bytecodealliance/cranelift)
- WebKit's [B3](https://webkit.org/docs/b3/)
- [DynAsm](https://luajit.org/dynasm_features.html)
