### ISSUE TITLE
Project 4 Proposal: Complexity Minimizer

### ISSUE THREAD

**Issue by kavoor** [sampsyo/cs6120#153]
**What will you do?**
This idea is based on an observation that programmers can be susceptible to writing inefficient algorithms. As such, we endeavor to take matters into the compiler's hands by optimizing the program at an algorithmic level. We aim to improve the asymptotic runtime of programs instead of simply compiling an efficient version of a given program. Specifically, we target making recursive functions memoized by using key elements of dynamic programming, and we want to do it at the IR level with LLVM. For example, we want to make a compiler pass that can change recursive fibonacci to iterative fibonacci. 

There is already work on external [automatic memoization](https://en.wikipedia.org/wiki/Memoization?fbclid=IwAR2cmBf7ZXKAEra1yZAruw_jWPJb8wPF-gbx-3V_AektUiEm7yTfigrdsi0#Automatic_memoization) that retains previous computations of a function (e.g., thunks) but we believe eliminating recursive function calls altogether improves both space and time performance. 

**How will you do it?**
We will first make this optimization work with recursive fibonacci and then generalize it to more complex cases, such as functions that take in multiple arguments or functions that need to store information in multiple dimensions. We will then generalize this to other DP patterns, and we will draw inspiration from algorithms coursework and LeetCode.

We will also apply constraints on the behavior of recursive functions we try to optimize. 

We will have a test-driven development that incrementally allows us to apply our algorithm to increasingly general cases.

We note that program synthesis is a tool for generating these types of optimal programs given a specification. However, we want our implementation to work at the IR level, which program synthesis may not be suitable for.

**How will you empirically measure success?**
Milestones:
1. Transform "brute force" recursive fibonacci to iterative fibonacci
2. Transform modified fibonacci-like programs (e.g., more arguments and more complex recursive calls)
3. Transform additional DP patterns beyond fibonacci 

We will define performance in terms of both time and space complexity.
**Team members:**
@liuhenry4428 @kavoor

**Comment by sampsyo** [comment]
Cool! It does occur to me that the standalone goal of "removing recession" is what tail call elimination (TCE) does. It obviously can't work on Fibonacci, however, because it's not tail-recursive—there are two recursive calls that have to be added together. So one way to phrase the problem might be in two steps:

1. Turn a complex recursive function into a tail-recursive one, possibly by adding additional parameters to the function. (This is the hard part.)
2. Do standard TCE. (This is not exactly easy but also not conceptually new ground.)

Good luck!
