### ISSUE TITLE
Project 4 Proposal: Quantum Vectorization

### ISSUE THREAD

**Issue by pbb59** [sampsyo/cs6120#154]
**What will you do?**
Quantum computations are inherently probabilistic, requiring multiple runs of the program to determine the correct answer. These runs are all identical, have no dependencies, and may not use all qubits available on the quantum computer. We propose a compiler pass to opportunistically schedule multiple copies of the same computation such that we can vectorize the control between runs.

**How will you do it?**
We will write a pass for a state-of-the-art [quantum compiler infrastructure](https://github.com/epiqc/ScaffCC) based in LLVM. We expect parallelization to be straight-forward because there are no dependencies between runs.

**How will you empirically measure success?**
This infrastructure includes 10 benchmarks and a built-in simulator (done classically). However, the simulator may not support SIMD operations like proposed in [this paper](https://dl.acm.org/citation.cfm?id=2694357). We will likely create a simple in-house simulator that counts the number of quantum control operations to show potential benefits.

**Team members:**
@Checkmate50 @pbb59

**Comment by sampsyo** [comment]
Sounds great! Here's hoping the Scaffold infrastructure doesn't turn out to be too gnarly.
