### ISSUE TITLE
Project 1 Proposal: Auto-differentiation

### ISSUE THREAD

**Issue by Chillee** [sampsyo/cs6120#16]
**What will you do?**
Implement auto-differentiation for the main function. We will extend the language to take in inputs for the main function and return values. We will then output the derivatives of the outputs wrt to the inputs when a special interpreter is invoked (which supplies input values).

**How will you do it?**
There's a couple different ways. We will start by implementing forward mode auto-differentiation (with dual numbers), then reverse-mode (by constructing a graph), and finally source to source translation (e.g. Julia's Zygote.jl) if we have time.

**How will you empirically measure success?**
We will write a short script to optimize a function (run it with inputs, take a step of gradient descent, continue), and test it on arbitrary functions. In addition, we will evaluate the standard properties of forward-mode vs reverse-mode differentiation to make sure that they need the correct number of function evaluations.

With:
@q-hwang

**Comment by sampsyo** [comment]
Nice! This seems very cool!

See also #14 and #8, which will also work on function calls. You might consider coordinating with them on the design of arguments and return values. In particular, arguments and return values from main seem like a great idea.
