### ISSUE TITLE
Project 4 Proposal: Bril Extension Framework

### ISSUE THREAD

**Issue by Dan12** [sampsyo/cs6120#166]
**What will you do?**

I will design and implement a framework for extending the Bril language.

**How will you do it?**

I will first survey all of the project 1 submissions that extended the Bril language and try and design a generic framework that allows me to extend as many of them as possible with minimal changes to the project 1 code that was submitted. I will then implement this framework and port several project 1 extensions to the framework.

**How will you empirically measure success?**

I will evaluate the ease at which the project 1 extensions can be implemented in the framework in a somewhat abstract way by noting the amount of work it took for each extension. Additionally, I will evaluate the type safety guarantees provided by the system as well as an abstract evaluation of how decoupled the extensions are from each other.

**Comment by sampsyo** [comment]
OK, cool! I’m excited to see how this turned out.
