### ISSUE TITLE
Project 1 Proposal: Exceptions for Bril

### ISSUE THREAD

**Issue by rolph-recto** [sampsyo/cs6120#17]
**What will you do?**
Add support for compiling exceptions in Bril. This is a stepping stone to adding support for compiling algebraic effects.

**How will you do it?**

* Add new instructions for changing the stack pointer
* Change interpreter to implement this
* Add to `ts2bril` compiler to support compiling TypeScript exceptions to Bril 

**How will you empirically measure success?**

I will write small benchmark TypeScript programs that contain exceptions and check how long they run.

**Comment by sampsyo** [comment]
Sounds cool and a little bit tricky! I'm interested to see how the design shakes out.

**Comment by sampsyo** [comment]
Closed in #32.
