### ISSUE TITLE
Project 1 Proposal: Bril Debugger

### ISSUE THREAD

**Issue by anastos** [sampsyo/cs6120#18]
**What will you do?**

Create a Bril interpreter that enables setting (conditional) breakpoints, stepping through instructions, and viewing/modifying the current state of the program. If we nail down the syntax/semantics for other people's language extensions (e.g. function calls) early enough, I can support those as well.

**How will you do it?**

I will create a CLI with a command language for completing the actions listed above. The debugger will keep a representation of the program itself as well as the current state of the program, and will modify the state in response to the commands. I'm open to suggestions of libraries for making good-looking CLIs.

**How will you empirically measure success?**

I will run the debugger on several Bril programs, testing that the program output is correct, and that the state at various program points is what it should be.

**Comment by sampsyo** [comment]
Cool! If I were you, I'd start with a straightforward GDB- or LLDB-like interface, which isn't fancy and just prints out lines at a time. Eventually, you can imagine doing a full-on TUI with curses or [curtsies](https://curtsies.readthedocs.io/en/latest/) or whatever, but I'd leave that for later.
