### ISSUE TITLE
Project 4 Proposal: Replacing different LLVM constructs with runtime functions

### ISSUE THREAD

**Issue by sa2257** [sampsyo/cs6120#189]
**What will you do?**
I'm making some template passes to replace instructions, basic blocks and functions with a runtime function call.

**How will you do it?**
I will create three passes, one each to replace an instruction, a basic block and a function.
These passes will insert a runtime function call which will evoke a function in a runtime library in C. C runtime libraries will also call Python functions.
I will implement some interesting functions in Python to motivate the use of templates.

**How will you empirically measure success?**
I will test couple of llvm construct replacements for the Machsuite and possibly some other benchmark suite.
I will also test performance metrics of using these runtime libraries to evaluate the tradeoff of using them.

**Team members:**
[@sa2257 ]

**Comment by sampsyo** [comment]
Hello! We can talk about this more "in person," but it would be useful to understand a little more detail about what these passes will look like. In particular:

- How will the pass know which instruction, block, or function to replace?
- What do you mean by "template"? Is this a C++ template?
- What counts as an "interesting" function?

I am also a little unclear on your evaluation plan. What will a successful test with MachSuite look like? How will you know that a replacement has been successful? Also, for performance, where do you expect the performance difference to come from? (And in which metrics exactly?)

**Comment by sa2257** [comment]
- Each of the templates will consist of the rudimentary features needed to replace each. An example for each will motivate how each of them will be selected to replace. But it is up to the user to write some code to do application specific selections.
- I use ’template’ loosely here. As a fill in the blanks pass to use for replacement. But I’m open to consider other strategies.
- ‘Interesting’ is used to say it’s not trivial as an arbitrary text print or something. 
- Evaluation is expected to test applicability to different benchmarks. Hence a successful test will show the replacement templates can be successfully used with a broad set of benchmarks. Success here has to be defined with the test, an example would be, replace an instruction in each benchmark with a python function that’s functionally the same.
- Performance aspect is not testing the specific implementation of the tests, but the broad approach of using runtime functions. It is provided as a feedback to potential users to inform when and when not to use this strategy.

**Comment by sampsyo** [comment]
Sounds good. I would recommend isolating the "should I replace this (instruction|block|function)?" computation into a C++ function/method that by default just returns `false`. Then the only thing the "user" needs to do is fill in that function to sometimes return `true`.
