### ISSUE TITLE
Project 1 Proposal: C Interpreter and Looping Construct

### ISSUE THREAD

**Issue by Bhargee** [sampsyo/cs6120#19]
**What will you do?**
Write a nice fast C interpreter for bril
**How will you do it?**
Use a tried and tested systems language to write an interpreter that will hopefully be faster by default. If I have time I want to implement control flow graph optimizations, specifically loop transformations. 
**How will you empirically measure success?**
I'll measure correctness and speedup against the bril repository reference programs.

**Comment by sampsyo** [comment]
Sounds good! See also #15, where the aim is to write an interpreter in Rust. That thread also has a link to some writing about fast interpreter implementation techniques.

> If I have time I want to implement control flow graph optimizations, specifically loop transformations.

Please leave this for a future project, where you'll be able to dig into compiler optimizations. Instead, focus just on interpreting whatever you get as input—so optimizations are left to a separate pass.

**Comment by sampsyo** [comment]
Closed by #40.
