### ISSUE TITLE
Project 1 Proposal: Compiling Bril to Wasm

### ISSUE THREAD

**Issue by cacay** [sampsyo/cs6120#2]
**What will you do?**
I will compile Bril programs to WebAssembly.

**How will you do it?**
I will write the compiler in Typescript. The main challenge will be turning arbitrary variable accesses into stack operations.

**How will you empirically measure success?**
I will test the Wasm code against the reference interpreter on example programs to check its correctness. I might also time them to see how much faster Wasm code is.

**Comment by sampsyo** [comment]
Great! I'm very excited for this.

FWIW, you could imagine doing a first pass where all stack variables are stored on the heap, and you have to load and store them every time. Then you could come back and do the stackification, which will hopefully make the code a lot smaller and faster.
