### ISSUE TITLE
Project 1 Proposal: Probabalistic Bril

### ISSUE THREAD

**Issue by orichardson** [sampsyo/cs6120#20]
**What will you do?**
Extend bril so that a program represents a family of distributions conditioned on an input, and write external tools to inference

**How will you do it?**

- Add a flip (and possibly continuous rand) primitive instruction;
- add a few lines in the interpreter to interpret this as built-in random
- extend the ts2bril compiler to do the appropriate thing with ts rand
- write a naive exact solver that just tracks the probability mass with vectors in the discrete case
- write an MCMC sampler, for probabalistic bril, loosely based on R2 https://www.microsoft.com/en-us/research/publication/r2-an-efficient-mcmc-sampler-for-probabilistic-programs/

**How will you empirically measure success?**
Write toy programs in typescript, and generate random well-formed bril programs that use the flip primitive. Verify that in each case the MCMC sampler, exact inference (when it completes before a threshold) and simple Monte Carlo sampling using the bril interpreter all yield the same result. Plot convergence curves, and number of samples until convergence within a threshold, against relevant structural features of the program (such as program length, run time, number of branches, number of flips, entropy of resulting distribution). Randomly select a small subset of the programs and verify that the inferred posterior is correct.

**Comment by sampsyo** [comment]
Very nice! This sounds like fun.

I assume Michael is part of this team? (I don't know his GitHub username.)
