### ISSUE TITLE
Project 1 Proposal: A Backend that translates Bril into C

### ISSUE THREAD

**Issue by xu3kev** [sampsyo/cs6120#21]
**What will you do?**
I'll build a backend that translates Bril into C language and then use GCC to compile and execute the program. As I can leverage GCC compiler optimization, I'm curious about its performance compared to other backends.

**How will you do it?**
I think most of it is straightforward because currently there is only one main function and I can use `goto` in C to implement `br` and `jmp`. One little tricky thing I can think of now is that a variable can be redefined to a different type (is it valid?), so I have to maintain type information myself during execution.

**How will you empirically measure success?**
Write some examples and check with the reference interpreter to see if the results are the same.

**Comment by sampsyo** [comment]
Sounds great! It would be interesting to compare the implementation complexity and results against groups that want to generate LLVM instead. See #11, #6, and #4.

> One little tricky thing I can think of now is that a variable can be redefined to a different type (is it valid?),

I think it would be sensible to call this an error and not support it.

**Comment by mpmilano** [comment]
I want to just quickly jump in here to point out that in C there's no "bool" anyway, so you'll be using an integral type to track booleans.  Traditionally that would be a char, but there's no reason it can't just be a normal int --- which would mean that your interpreter can use the same C datatype for `bool` and `int` if you want to!

**Comment by xu3kev** [comment]
@mpmilano I think you're right. Thank you!
