### ISSUE TITLE
Hi, Professor, may I ask what's the difference between CS6120 beta and gamma ? 

### ISSUE THREAD

**Issue by yumindeckard** [sampsyo/cs6120#217]
CS 6120: Advanced Compilers β
CS 6120: Advanced Compilers γ

Hi, Prof. Sampson,

I googled the course, but there are 2 results which are very similar. May I ask the difference between them ? Thanks.

Regards
Yumin

**Comment by yumindeckard** [comment]
Please delete this issue. I asked a stupid question. Sorry.

**Comment by sampsyo** [comment]
No worries! In case anyone else stumbles across the issue, the answer is that these were two different offerings of the course (2019 and 2020).
