### ISSUE TITLE
Project 1 Proposal: embedded Bril

### ISSUE THREAD

**Issue by mpmilano** [sampsyo/cs6120#22]
I plan to Implement a Bril interpreter in C++ twice: once as a runtime mechanism, and once as an embedded language within C++ itself. 

This will be accomplished with many, many templates.  C++ has a `constexpr` evaluation framework allowing C-style runtime code to run instead at compile-time.  The runtime-oriented Bril interpreter will take advantage of standard OO paradigms; the compile-time one will take advantage of [my still in-progress library](https://github.com/mpmilano/better-compiletime) for writing compile-time interpreters. 

Success will be measured by (a) whether Bril's semantics are suitable to the constexpr-style evaluation currently supported by C++-17, and (b) if they are, what the compile-times of this project are, what the resulting runtime of the compiled code is, and whether a compiled-in program text running through the Bril embedded implementation significantly outperforms the same text running through the (presumably heavily inlined) interpreter.

**Comment by sampsyo** [comment]
Sounds very very cool. I assume that you will need an preprocessing pass where you convert the JSON representation of a Bril program to C++ code that uses the templates? Or will the interpreter start with a string and do the JSON parsing itself? :scream:

**Comment by mpmilano** [comment]
The plan is straight from the string.  No command needed other than a single run of the C++ compiler.  Though I reserve the right to give up on straight-from-json since nobody's written a compile-time json parsing library that I can see so far, and I'm not 100% sure how complicated a json parser is supposed to be.

**Comment by sampsyo** [comment]
Neat. Good luck with the JSON thing, but I heartily endorse having a fallback plan to skip that step.

**Comment by mpmilano** [comment]
Huh, apparently someone actually has [at least started](https://github.com/lefticus/constexpr_all_the_things/blob/master/src/include/cx_json_parser.h) a `constexpr` json parser for C++.  Looking forward to trying it out!
