### ISSUE TITLE
Project Proposal: Speculative Execution in FuTIL

### ISSUE THREAD

**Issue by tedbauer** [sampsyo/cs6120#223]
**What will you do?**

I'm planning to implement speculative execution in FuTIL for `if`/`else` statements, using the approach of this paper: https://dl.acm.org/doi/pdf/10.1145/3289602.3293914.

**How will you do it?**

I will implement this as a pass in the FuTIL compiler. The pass will find `if`/`else` statements in the `control` section of FuTIL programs, and generate FuTIL code that effectively implements the "Branch Speculator" described in the paper linked above. This will involve placing `Speculator`, `Commit` and `Save` groups, and control logic orchestrating these groups.

**How will you empirically measure success?**

I'm thinking of simulating the PolyBench kernels that were implemented for the FuTIL paper, comparing simulated cycle counts with and without this pass enabled, similar to how the static timing optimization pass is evaluated.

**Comment by sampsyo** [comment]
Very cool! This is ambitious, of course, and somewhat open ended. I think it's important to spend the early part of this project narrowing things down and making them concrete for the remainder of the work.

**Comment by sampsyo** [comment]
Closed in #246.
