### ISSUE TITLE
Project Proposal: Relational Algebra Compiler

### ISSUE THREAD

**Issue by ankushrayabhari** [sampsyo/cs6120#225]
**What will you do?**
The way most existing SQL engines work is by first converting SQL to a tree of [relational algebra](https://en.wikipedia.org/wiki/Relational_algebra) operators and then interpreting that tree. Interpreting means that each operator has a produce function. When you call it, the operator will call a produce function from its child operators which return a batch of tuples (or empty if it's done), process that batch (filter by some condition, execute a map function, join data, etc.), and then return the processed batch.

While easy to implement from a system point of view, this leads to a lot of overhead as you have a function call boundary at each operator. Instead, by generating actual code, we minimize the overhead of this and keep values in registers for as long as possible.

For example, this would be what is executed for the interpreted version of `op = Filter(Scan(T), x>5)`
```
output = []
while (true) {
  batch = op.produce()
  if (batch.empty()) break;
  output.append_all(batch)
}

GT.evaluate() {
   l = left.evaluate()
   r = right.evaluate()
   return l > r;
}

Filter.produce() {
   batch = child.produce()
   output = []
   for (x in batch) {
      if (expr.evaluate(x)) {
        output.append(x)
      }
   }
   return output;
}

Scan.produce() {
  return next batch of T
}
```
This is really backward. The following equivalent code will be much faster as it avoids all these virtual calls and keeps values in registers for longer.
```
output = []
for (x in T) {
   if (x > 5) {
     output.append(x)
   }
}
```
Our goal is to for a given relational plan, generate the code for the second version, compile and execute it. 

**How will you do it?**
Broadly, the implementation will follow these papers:
https://www.vldb.org/pvldb/vol4/p539-neumann.pdf
https://db.in.tum.de/~kersten/Tidy%20Tuples%20and%20Flying%20Start%20Fast%20Compilation%20and%20Fast%20Execution%20of%20Relational%20Queries%20in%20Umbra.pdf?lang=en

Rather than a single produce interface to "pull" tuples from the child operators, you use a produce/consume interface. Produce tells the operator to generate code that iterates over it's result while consume allows you to "push" tuples to that operator. This ends up generating tight loops around the pipelines of the program.

While a lot of paper 1 and paper 2 focus on strategies to reduce compilation time (immediately generate LLVM, generate custom IR, restrict LLVM compilation passes, etc.), I'll skip that and directly generate C++ code. My goal is to ideally use the data structures outlined by the second paper: proxy structures that generate code to reduce the complexity of the code generator, wrapper types, linking directly with the database types so I can have a maintainable code base for extending after this course.

I'll implement an in-memory column store as the storage back end.

My goal is to first get this working for just tables with integer types and then progressively add in other types like dates (just end up being ints), strings (ideally use dictionary encoding to just keep them as ints), etc.

I'll limit joins to equi-joins for now and then use cross products for more wild join conditions.

**How will you empirically measure success?**
Depending on how many types the system supports, I'll take an existing benchmark suite like TPC-H or JOB and then filter them down to the compatible queries and run them or prune out the features that I don't support and run it.

I'll plan on finding a similar database that is interpreted and execute that.

**Team members:**
Just me.

**Comment by sampsyo** [comment]
This sounds really great—and quite ambitious in total scope. Looking forward to it.

**Comment by ankushrayabhari** [comment]
Code: https://github.com/ankushrayabhari/kushdb/
