### ISSUE TITLE
Project Proposal: Type and Effect System

### ISSUE THREAD

**Issue by kq-li** [sampsyo/cs6120#227]
**What will you do?**
I hope to implement a simple interpreted language with a type and effect system. To my understanding, this has two potential facets: a static system, where "effects" are a kind, and a runtime augmentation, where an effect is encoded as metadata on a value. The static system will allow for more careful programming (e.g. explicit marking of side effects) as well as enabling smarter optimizations (e.g. marking pure/idempotent function calls). The runtime support would allow for things like algebraic effect handlers, where functions can return to their callers with special values and be resumed.

This project was partially inspired by [1](https://www.janestreet.com/tech-talks/effective-programming/), [2](http://web.cs.ucla.edu/~todd/research/tldi09.pdf), and [3](https://www.ccs.neu.edu/home/amal/course/7480-s12/effects-notes.pdf), with additional inspiration from the question of to how compilers might be able to take advantage of types (and effects).

**How will you do it?**
I plan on implementing the static system first; namely, the language's frontend and typechecker. Then, I want to demonstrate the benefits by implementing simple optimization passes that take advantage of the side effect information. As a later goal, I'd like to also extend this system with user-defined effects and runtime support.

I'm still fleshing out the actual language specification, but I will start simply with expressions over types like `int` and `bool` and control flow statements with the two side-effect statements `output` and `input` to write to `stdout` and read from `stdin`. This should be sufficient to demonstrate some optimizations based on idempotence and reordering. Then, I want to implement support for runtime effects, allowing dynamic detection of what effects occurred -- this would use some sort of pattern matching and a special `return` construct. A stretch goal would be to implement a memory extension with arrays and explore some of the memory-based effects discussed in the above sources. 

**How will you empirically measure success?**
As this project hinges on a new language, there won't be existing benchmark suites or statistics to compare against. I plan on writing my own benchmarks for the purposes of testing language correctness and optimization performance, but further suggestions on how to evaluate the project's success are very welcome.

**Team members:**
Just me

**Comment by sampsyo** [comment]
OK, sounds good! I assume this language will be higher-order, which makes the type system more interesting? If it's meant to be first-order, a straightforward implementation might be really simple.
