### ISSUE TITLE
Project Proposal: Loop Unrolliing in the Networking Domain

### ISSUE THREAD

**Issue by stp59** [sampsyo/cs6120#228]
Samwise Parkinson
Github username: stp59

# Packet Header Parser Unrolling

## Motivation

P4 is a DSL used to program the forwarding plane of networking devices, and it includes a sublanguage for parsing packet headers which resembles a state machine. The sub-language consists of states, which a blockes of code followed by transition statements. Because of the nature of the domain, the target machine languages for these programs is typically not turing complete, whereas it turns out the the parser sub-language [is](https://github.com/p4lang/p4-spec/issues/46). The language specification "resolves" this issue with a vague suggestion that parser loops should be unrolled at compile-time, or that loops that are not clearly finite should be rejected by some sort of static analysis pass. This makes the formal specification and verification of the parser sub-language a challenge.

## Proposal

I wish to understand loop unrolling in this domain more closely. To this end, I will modify bril to resemble selected features of the P4 parser sub-language and implement a version of loop unrolling. The implementation should:

* check the program for certain basic conditions indicating that any loops are finite, and fail with  a helpful error message if not

* compute the number of unrollings needed to make the loops finite

* perform a loop unrolling transformation, and output an equivalent bril program without any loops in the CFG

I will start with very restrictive conditions checking if the loops can be unrolled, and I will try to keep the modified version of bril as simple as possible in order to focus on implementing loop unrolling for a arbitrary number of loop copies. This done, I will search for ways to weaken the conditions checking if the loop is finite, keeping common use-cases of P4's parser language in mind.

## Evaluation

Over the course of implementation, I will compile a collection of programs in the modified version of bril. For positive test cases, I will check that the input and output programs behave the same using the bril interpreter (I may need to implement my own interpreter for the modified version). I will also search for tricky edge cases which test that my conditions for unrolling are implemented correctly. Some of the positive test cases can be derived from real-world P4 programs.

**Comment by sampsyo** [comment]
Sounds cool enough! The big question, of course, is how hard the compiler will "try" to identify static loop bounds. It's uncomputable in general, and pretty easy to capture the very simple cases, so I imagine you'll want to shoot somewhere in the middle of "just the trivial cases" and "every loop, every time."

Also, while targeting a P4-like Bril variant is fine, I wonder whether you might get more satisfaction out of implementing this for real P4 programs. Like, maybe you could do a source-to-source (actually, AST-to-AST) transformation within [Petr4](https://github.com/cornell-netlab/petr4).

**Comment by stp59** [comment]
Interesting...I had initially moved away from this idea because P4 has so many moving parts. However, if you think it would still be a manageable scope, it could be really useful for Petr4 later. You think its still feasible?

**Comment by sampsyo** [comment]
Sure! It's at least worth trying and giving up if it's too complicated. Remember that you're allowed to pick a restriction/subset of the full P4 language to support to make it tractable!

**Comment by stp59** [comment]
Implemented in Petr4; code is in the petr4 repository in a PR [here](https://github.com/cornell-netlab/petr4/pull/252)
