### ISSUE TITLE
Project 1 Proposal: Brill code generator

### ISSUE THREAD

**Issue by g-c-c** [sampsyo/cs6120#23]
**What will you do?**
Build a frontend for generating Bril code from Julia!

**How will you do it?**
Use Julia's parsers and [ASTs](https://docs.julialang.org/en/v1/devdocs/ast/) to write an interpreter, and return the equivalent expression in Bril. 

**How will you empirically measure success?**
Check the correctness of generated Bril code against tests written in Julia. Test also for Julia capabilities that currently have no counterpart in Bril, and ensure the generator returns an appropriate output.

**Comment by sampsyo** [comment]
Sounds good! Please keep in mind that you'll be translating a very small subset of Julia—you can just produce a reasonable error message for _lots_ of parts of the language and just support whatever's convenient to implement.
