### ISSUE TITLE
Project Proposal: Bril Frontend for Mini-Rust

### ISSUE THREAD

**Issue by evanbenadler** [sampsyo/cs6120#230]
**What will you do?**
I will implement a small Rust-like language which compiles into Bril. The language will use ints and bools as primitive types, and will also have objects (when I took CS 4120, we didn't implement objects due to the Covid pandemic, so this is my chance to finally implement it). The "Mini-Rust" implementation will do just enough to match the semantics in Chapter 4.1 (What is Ownership?), 4.2 (References and Borrowing) and 10.3 (Validating References with Lifetimes) of [the Rust Book](https://doc.rust-lang.org/stable/book/). 
This includes Rust's ownership rules:
- Each value in Rust has a variable that’s called its owner.
- There can only be one owner at a time.
- When the owner goes out of scope, the value will be dropped.
and Rust's reference rules:
- At any given time, you can have either one mutable reference or any number of immutable references.
- References must always be valid.

**How will you do it?**
To be clear, I'm not (yet) a Rustacean, so to really start attacking this, I first need to deeply internalize the semantics of Rust that I'm implementing. In other words, I can't yet describe what I'll do in detail. But I do know that I will use OCaml as my implementation language and ocamllex and Menhir for lexing and parsing. Also, I will rely on the Bril memory extension, calling `alloc` on Object construction and `free` inside the Rust `Drop` function. 

**How will you empirically measure success?**
In Chapters 4.1, 4.2, and 10.3 of the Rust book, the semantics are explained with many code snippets. I will run all these code snippets with my implementation and make sure I get the correct output or the expected error message. In addition, I will write test programs which implement data structures to evaluate correctness. I'm not sure if there's a good way to evaluate performance, but performance is not a big concern for this project anyhow.

**Team members:**
Just me

**Comment by evanbenadler** [comment]
I think I can implement objects using either the record types or the fixed length array Bril extensions

**Comment by sampsyo** [comment]
Neato! Implementing borrowing will, I'm sure, be a significant challenge by itself. It also occurs to me that you will want to consider extending Bril… so I would start as early as possible to find out where these Bril gaps are. I would be happy to help recommend ways to work around the missing pieces (or how to add them without too much fuss).

See also #229!
