### ISSUE TITLE
Project Proposal: Performance prediction of loop pipelining using LLVM

### ISSUE THREAD

**Issue by Sibylau** [sampsyo/cs6120#231]
**What will you do?**
Loop pipelining is an important optimization technique commonly used to improve the performance of applications. With the help of High-Level Synthesis tools, programmers can simply put a pragma in their C/C++ code to enable loop pipelining in hardware. However, programmers at early stage don't have much information on the performance of loops they write. If the specified pipeline initial interval (II) cannot be achieved, the HLS tools will throw out messages at least after running synthesis, which can take hours or even days for a large design. In this project, I want to perform quick analysis of the performance for loop pipelining. It will provide useful information about the pipelined loop, including minimum II, memory dependence locations, etc. These quick feedbacks will help programmers iterate their designs in a much faster way. I borrowed some interesting points in the work [gem5-SALAM](https://www.microarch.org/micro53/papers/738300a471.pdf), and reduced the workload to analyzing a loop pipelining case. 

**How will you do it?**
There are two ways of analyzing loops, one is doing it statically and another is dynamically. The polyhedral model is one powerful static analysis approach of extracting dependences in loops and predicting the minimal II according to the maximum dependence distance. However, polyhedral analysis requires the loops to be in Static Control Part (SCoP) form, which is a strong restriction. If there happen to exist an array access `a[i*i]` where the index is nonlinear to a loop iterator, polyhedral analysis unfortunately cannot handle the case. 

In this project I hope to do some dynamic analysis on loops. The analysis is based on the formula: `MII = Max(ResMII, RecMII)`, where `RecMII` is the minimum II bounded by loop-carried dependencies and `ResMII` is the minimum II bounded by resource limitations. Inspired by dynamic LLVM runtime engine in [gem5-SALAM](https://www.microarch.org/micro53/papers/738300a471.pdf), I will probably use a _reservation queue_, a _compute queue_ and a _memory_ queue to try to model the run time behavior. As each instruction is added to the _reservation queue_, the dependence analysis will check the in-flight _compute_ and _memory_ queue elements to determine whether the dependences meet and the instruction can be launched. The instructions manipulating local registers which can be resolved by the simulating engine will be put in the _compute_ queue. Memory instructions will go to the _memory_ queue. The flow takes in a default device-specific configuration file, which defines resources constraints. Users can also modify the configuration according to their needs. Since I don't have gem5 involved (I can consider if time permits), the memory model will be presumably simple. Actually most of the parameters in the configuration file will be obtained from the HLS tool.

**How will you empirically measure success?**
I will compare the prediction results against Catapult HLS tool, an ASIC HLS tool from Mentor (a small possibility that I'll use Vivado, if Catapult behaves weirdly). I will start from simple handwritten examples to help build up the correct funtionality. Accuracy is supposed to be the first priority of metrics. In the end I hope to evaluate the accuracy on some simple benchmarks in [PolyBench](http://web.cse.ohio-state.edu/~pouchet.2/software/polybench/) or [MachSuite](https://breagen.github.io/MachSuite/) against HLS results to prepare for potential realistic use.

**Team members:**
Just me.

**Comment by sampsyo** [comment]
Sounds cool! What you've described says, in my view, how you'll decide the pipelining strategy for a given loop. However, your motivation says you're interested in how to communicate this information back to the programmer. I'd be interested in more details about what form you think that information should take—what is the information a programmer is looking for when they want to "fix" their II? Or is the idea just to quickly guess the II before running the code through a real HLS toolchain?

**Comment by Sibylau** [comment]
Thank you! I want to analyze the ResMII and RecMII given the coding style and resource restrictions provided by the programmers. I hope the output will include both II numbers and some reasoning. Specifically for ResMII, the information include which sets of array accesses become the II bound (programmers may consider merging the reading memory accesses, or manually doing some optimizations like [scalar replacement](http://www.cs.cmu.edu/~mihaib/research/odes05.pdf) to push II smaller), whether II is bounded by frequent I/Os (maybe consider packing data), etc. For RecMII, the output will be where the longest loop carried dependence lies in and how to possibly reduce the dependence chain. And since the II is the maximum of ResMII and RecMII, only the bottleneck issue will be exposed to the programmers. Typically HLS tools will provide these reports at least after synthesis. If the programmers want more accurate performance results, they'll even need to wait after finishing co-simulation. I hope to give some useful (hopefully) early estimation to enable faster iteration of HLS coding.

**Comment by sampsyo** [comment]
Awesome; that kind of feedback seems very useful.

**Comment by sampsyo** [comment]
Finished in #254.
