### ISSUE TITLE
Project 1 Proposal: Vril (Vector Bril)

### ISSUE THREAD

**Issue by hcp922** [sampsyo/cs6120#24]
**What will you do?**
The idea is to have support for a high level programming language construct to represent vector data structures. This construct will have a one-to-one mapping to Bril IR array types the language also has associated vector operations. The main motivation of this construct and its associated operations is to by-pass the front-end of the compiler that would try to detect data-level parallelism, and automatically generate vector code. Instead, we are interested in focusing on the back-end optimizations of this vector types and vector operations.

**How will you do it?**
We need to define a new type "array of ints" to represent the vector types. We want these to have variable length.  To start, we would like to add to the list of Bril instructions their corresponding vertical and horizontal vector operations: "vadd" and "vredadd", for "add".

**How will you empirically measure success?**
After successfully implementing the new type and operations, we will code a few micro-benchmarks that utilize the language construct and their functionally identical scalar version, to generate their corresponding DFGs. To measure sucess, we want to make two observations: a) the two DFGs will contain a similar shape and the same number of basic blocks (BB), and b) the scalar program should be hopping the BBs in the DFG more times than the vector program. In particular, the BBs of the DFG involved in the `for-loop` part of the program should be hopped _vector-length times_ more in the scalar program than the vector one.

With @sa2257 & @qtt2 (audit).

**Comment by sampsyo** [comment]
OK, sounds pretty cool! To be clear, your evaluation plan sounds like it needs two versions of the code:

- Scalar array code that loops N times, where N is the length of a big array.
- Vectorized code that loops N/K times, where K is some vector length.

To be clear, *neither* of these is possible in Bril yet. You'll need to add both standard array constructs (including read & write indexing) and then also some way to do vector operations.

You also mentioned that you want to have a variable vector length. It would be good to think carefully about how that will work—i.e., how the vector length will be specified by the program and used by the interpreter or some other backend.

Please also chat with @pbb59, who has a similar proposal in #7.
