### ISSUE TITLE
Project 1 Proposal: Add record types to Bril

### ISSUE THREAD

**Issue by liuhenry4428** [sampsyo/cs6120#25]
**What will you do?**
We will add support for mutable record types. A record will have a set of named fields with types, and those types can include record types. We are also thinking about adding support for constant record types (by adding a const keyword) to designate a record as immutable. @sampsyo what do you think about this? 

**How will you do it?**
We will edit the Bril interpreter, and also bril2json for tooling.

**How will you empirically measure success?**
We will consider this project successful if we add working record types that integrate completely with the existing types, such that any valid type can be used in a record.

Working with Katy Voor (kev29)

**Comment by sampsyo** [comment]
Sounds good! I'd probably just pick mutable or immutable and stick with it—that's probably enough for this project.

I think a big choice you'll want to make is whether record types will need to be declared up front and then used by name or just listed inline, without a central declaration. In the former case, you can decide whether the type system should be nominal or structural.

**Comment by sampsyo** [comment]
Closed in #31.
