### ISSUE TITLE
Project 1 Proposal: Static type checking for Bril

### ISSUE THREAD

**Issue by ElaineJiang** [sampsyo/cs6120#3]
**What will you do?**
We will implement a static type checker for Bril. It can be used to find type errors and uses of undefined variables.

**How will you do it?**
We will first go through the Bril language to find all types existing and the corresponding typing rules. Then we will implement the type checker in ts based on the rules designed.

**How will you empirically measure success?**
There are two general cases for type errors. Either no type is defined before use, or the use case violates the predefined type. Thus, we test the type checker also in two folds. A bunch of test files would to be written covering non-predefined types, violation of typing rules for all types, and well-typed code as well.

Project with @tissue3 and @neiladit

**Comment by sampsyo** [comment]
Awesome; this sounds great! If I can offer one small hint, I think it should be an error to define the same variable twice with different types within the same function.
