### ISSUE TITLE
Project Proposal: Bril Bytecode Interpreter

### ISSUE THREAD

**Issue by susan-garry** [sampsyo/cs6120#304]
**What will you do?**
We will implement a bytecode interpreter for bril using C. If we have time, we will extend this to emit assembly, and target x86 and ARM.

**How will you do it?**
First we will create a bytecode for bril. This will limit the size of the program in terms of the number of variables, labels, and instructions for functions, but as of yet there does not exist a bril program that uses $2^{16}$ variables. It will also be challenging to support the speculation extension of the bril language, but ideally we would like to include this as well. Translating to assembly should be relatively easy due to the structure of the bytecode.

**How will you empirically measure success?**
Having a working interpreter is a must. We also aim for the interpreter to be faster than the provided brili interpreter, and for the assembly to be even faster than that. 

**Team members:**
@charles-rs and @susan-garry

**Comment by sampsyo** [comment]
This sounds super cool. I like the fact that you have a "telescoping" project scope: you can start out with the bytecode format & interpreter and, depending on how challenging that turns out to be, tack on as much of a compiler as you want.

Here's an extra challenge, should you choose to accept it: thoroughly document the bytecode format! And provide a standalone JSON<->bytecode translator of some sort. We could merge this into the main bril repository here, and I am sure that people would have a good time building on the bytecode format in the future—even if they don't want to use your interpreter, they may want a compact/efficient serialization format.

**Comment by charles-rs** [comment]
Some preliminary work [here](https://github.coecis.cornell.edu/cs897/fast-bril).

We have documentation for the bytecode, as well as the bril -> bytecode and bytecode -> bril translations, though these aren't thoroughly tested and currently rely on the type-inference program. This shouldn't be necessary in the end but i got sick of working on that part for now.

The bytecode interpreter works on the benchmarks, but they don't cover many edge cases, so there are likely still bugs. It is MUCH faster than the reference interpreter, though I haven't compared it to the rust one yet. Currently clocking ~100MHz (in terms of bril instructions) on the ackermann example, which is admittedly not a very diverse set of instructions.

Compilation to armv8-a is MOSTLY functional, but there are some control flow bugs it seems, and memory + ssa are not supported yet.

Nothing supports speculation.

The code is criminally underdocumented.

One thing i'm not so sure about is the way types work in the bytecode, it's very rigid right now, and not very extensible, but at the same time, it is possible to get rid of even more types if we are willing to give up on translating back to bril w/out some serious inference. It seems as if the types fit nicely into a few unused words right now, so maybe not an issue? Also not quite sure about the desirability of having "dead" bytes in the bytecode which are there for ease of alignment

**Comment by sampsyo** [comment]
Awesome!! Do you think now would be a good time for me to read those docs for the bytecode format? Not that you need to do this now, but eventually it would be cool to get those in a Markdown format (perhaps with the assistance of [Pandoc](https://pandoc.org)?) so we can put them into the "official" Bril documentation.

You mentioned that compilation to armv8-a doesn't support memory or SSA. Supporting memory seems like a good idea, but I would _not_ bother supporting SSA directly. Maybe this is obvious, but the "proper" thing to do is to do register allocation *while* going out of SSA form. So you could consider writing a Bril-to-Bril pass that eliminates SSA while choosing  Bril variable names that map onto ARM register names. Then this restricted form of program would be straightforward to compile to assembly. The advantage of doing it this way is that your interpreter can still "support" SSA by removing it first, but your pass becomes a reusable module that other projects could incorporate too.

The "extensible types" thing in the bytecode is a great question. It seems like there is, in general, a big trade-off when designing the bytecode with respect to extensibility: will it support *only* the sets of opcodes/types that you currently know of, and therefore be more efficient/specialized, or will it support *the full flexible base Bril spec*, perhaps at the cost of speed? One way to cut the Gordian knot would be to design the format to it bakes in a set of opcodes/types, but *the format itself* can be extended. Like, it's possible to add more mappings for new kinds of types, but the strings are never stored anywhere. So round-tripping back to JSON is still possible, but only for the set of types that you baked into the converter and format ahead of time.

**Comment by charles-rs** [comment]
Yes it would be great if you could glance over the docs! They are in a kind of risc-v ish style latex document right now!

Yeah this makes sense w/ SSA, and it would make nontrivial register allocation easier! (could be cool to see the performance gain of this).

right now the type representation is very rigid, but is able to represent pointers to a depth of 2^14, which is likely more than ever necessary, so it could be possible to add a flag for "other type" where it then uses more space, allowing for extension, not sure rn.
