### ISSUE TITLE
Project 1 Proposal: Floating Points and Compiling Bril to LLVM

### ISSUE THREAD

**Issue by Checkmate50** [sampsyo/cs6120#4]
**What will you do?**
I will implement a compiler from existing Bril code to the LLVM-IR.  This compiler will include selecting integer and floating-point operations based on provided numeric representation. As people implement new features, I'll try to keep this compiler up-to-date.

**How will you do it?**
I'll write the compiler in typescript.  I'll also update Bril with a floating-point type, along with a mechanism for differentiating `int` from `float` at compile time.

**How will you empirically measure success?**
For each file, I'll compile to LLVM and test the resulting code.  I'll start with the existing test code first, then add a couple of floating-point tests.

**Comment by sampsyo** [comment]
Nice! See also #6, where there's a little more discussion about an approach to LLVM generation. Also, you and @Dan12 are welcome to work together on this if you like, but you of course don't have to. But if you do, coordinating the integer and FP parts of the design might be a good division of labor.

**Comment by Checkmate50** [comment]
Note that (as discussed with @sampsyo), this project proposal was changed to add floating points and _fixed-width_ arrays to Bril rather than LLVM support (due to the large number of Bril->LLVM projects).  For fixed-width arrays, I will add and test declaration, assignment, and indexing.
