### ISSUE TITLE
Project 1 Proposal: Manually Managed Memory

### ISSUE THREAD

**Issue by dz333** [sampsyo/cs6120#5]
**What will you do?**
I will add manually managed pointer types to the Bril parser and interpreter, which include type-based `alloc`, `free`, `read` and `write` operations.

**How will you do it?**
I will add new syntax for the corresponding instructions and add pointer types to the language. Pointer types must be parameterized on another type (e.g. Pointer<Pointer<Int>>).
In the interpreter, I will create an object that manages pointers and their values. The exact implementation here can have significant effect on the interpreter performance.

**How will you empirically measure success?**

I will write several test programs that use pointers and verify that they produce expected values.
Furthermore, I will add tests that repeatedly allocate/free significant amounts of memory to test the overhead of the interpreter allocation implementation.

**Comment by sampsyo** [comment]
Sounds great!!

I think @hackedy said he was interested in something similar. You could work together if you like.

**Comment by dz333** [comment]
@hackedy and I will work on this together :)

**Comment by dz333** [comment]
Here is our pull request: #30
