### ISSUE TITLE
Project 2 Proposal: Strength reduction with loop invariant code motion

### ISSUE THREAD

**Issue by ElaineJiang** [sampsyo/cs6120#52]
**What will you do?**
We will implement a strength reduction compiler optimization with loop invariant code motion and induction variable analysis. The goal is to replace the expensive operations with equivalent and cheaper operations (i.e., less execution time/power/area).

**How will you do it?**
We will first go through the code to identify all the loops and recognize the characteristics of local values within those loop. Here, we want to find out:
    * loop invariants (values not changed within the loop body)
    * induction variables (values iterated each time through the loop)
Now, as we have identified all the loop invariants and induction variables, we can hoist the loop invariants outside the body and replace some expressions inside the loop with the constants. After that, substitute expensive expressions composed of induction variables with cheaper operations (i.e., multiplication -> addition).

**How will you empirically measure success?**
As we are trying to reduce expensive operations to cheaper ones, so the performance can be measured as "the total number of arithmetic operations of each kind" (e.g., #addition, #multiplication) before and after code optimization. Also, we can run the test programs before and after code optimization to derive a wall clock speedup.

**Team members:**
 @tissue3 @neiladit

**Comment by sampsyo** [comment]
Sounds good overall! However, one clarifying question: to replace multiplies with additions in loops, I assume you're talking about ether array indexing or pointer arithmetic? Needless to say, the original Bril has neither. What extension will you use?

Here are some things to keep in mind:

- Wall-clock speedup, or some approximation of it, is the more important thing. Just reducing the number of multiplies is only a means to that end.
- A small terminology thing: "loop invariants" are something else. Say "loop-invariant code" to refer to code that does the same thing on every iteration.

**Comment by sampsyo** [comment]
Also, as you already noted, this proposal is related to #50. You might want to consider comparing your results after it's all over.

**Comment by tissue3** [comment]
> Sounds good overall! However, one clarifying question: to replace multiplies with additions in loops, I assume you're talking about ether array indexing or pointer arithmetic? Needless to say, the original Bril has neither. What extension will you use?
> 
> Here are some things to keep in mind:
> 
>     * Wall-clock speedup, or some approximation of it, is the more important thing. Just reducing the number of multiplies is only a means to that end.
> 
>     * A small terminology thing: "loop invariants" are something else. Say "loop-invariant code" to refer to code that does the same thing on every iteration.

Though it might change once we start the implementation of this project, we plan to use pointer at this moment.
