### ISSUE TITLE
Project 2 Proposal: Trace Scheduling for Bril

### ISSUE THREAD

**Issue by rachitnigam** [sampsyo/cs6120#56]
**What will you do?**
(1) Extend the interpret to execute multiple instruction in the same "cycle" (corresponding to a step of the `interpret` function)
(2) Implement a heuristic based [trace scheduler](https://en.wikipedia.org/wiki/Trace_scheduling) for Bril.
(3) (Stretch goal) Expose hooks for choosing heuristics and use [OpenTuner](http://opentuner.org/) to see if we can come up with better traces. 

**How will you do it?**
(1) Extend the interpret with a `guard` execution to detect failed executions.
(2) Generate traces by assuming all branches are going to be true and patch the control flow to revert to slow paths if it turns out to be false.
(3) Write scripts to drive opentuner.

**How will you empirically measure success?**
For (1) and (2), we will measure the execution time of programs in the extended interpreter and compare them to the time for the trace-scheduled code. We will also measure how long we stay in a given trace.

For (3), we will expose the aforementioned metrics as optimization objects and try to maximize them. 

**Team members:**
@sgpthomas

**Comment by sampsyo** [comment]
Sounds very cool!

> Extend the interpret to execute multiple instruction in the same "cycle" (corresponding to a step of the `interpret` function)

This actually sounds somewhat subtle to get right—are you saying that the interpreter will always execute 2 instructions, or will it try to detect and resolve dependencies by dynamically scheduling the instructions?

You might consider *not* doing this part and just counting higher-level metrics like the amount of time spent in traces and such…

> Generate traces by assuming all branches are going to be true and patch the control flow to revert to slow paths if it turns out to be false.

An even cooler (and possibly more effective) way might be to use profiling to get a better "direction" guess for each branch.
