### ISSUE TITLE
Project 2 Proposal: loop invariant code motion

### ISSUE THREAD

**Issue by rolph-recto** [sampsyo/cs6120#58]
**What will you do?**
Loop invariant code motion

**How will you do it?**
We will add to the Bril typescript codebase (computing dominators, dataflow analysis for reaching definitions, etc.).

**How will you empirically measure success?**
We will instrument the Bril compiler to measure the number of instructions executed by the interpreter. The fewer instructions the interpreter executes, the better the optimization performs.

**Team members:**
@g-c-c

**Comment by sampsyo** [comment]
Sounds good to me! Good luck.

**Comment by sampsyo** [comment]
Closed by #89.
