### ISSUE TITLE
Project 2 Proposal: Global Value Numbering

### ISSUE THREAD

**Issue by avanhatt** [sampsyo/cs6120#59]
**What will you do?**
We will implement global value numbering (per-function, across basic blocks) for Bril programs.

**How will you do it?**
We first need to implement dominator tree construction and conversion to SSA. We will then implement the value partitioning algorithm from [Briggs, Cooper, & Simpson 1997][]. Finally, we’ll add an extension for constant propagation. 

**How will you empirically measure success?**

Our evaluation will consider two metrics (in order of increasing ambition). In particular, we will compare these metrics on the same program before and after our optimization. Will hope to use the TypeScript front end to create and share a large benchmark suite, based in part on porting benchmarks from SPEC and other existing suites.

- Code size (the fewer Bril instructions, the better).
- Runtime performance of programs (either via measuring the interpreted Bril execution time, or by measuring the machine code generated from the existing LLVM backend).

In addition, we hope to extend our property-based testing from Project 1 to generate programs that have redundant subexpressions, in order to fuzz-test our implementation. 

**Team members:**
@gyauney 

[Briggs, Cooper, & Simpson 1997]:http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.36.8877&rep=rep1&type=pdf

**Comment by sampsyo** [comment]
Excellent! This has the potential to be a very good optimization. Looking forward to it!
