### ISSUE TITLE
Project 1 Proposal: Bril to LLVM (in OCaml?)

### ISSUE THREAD

**Issue by Dan12** [sampsyo/cs6120#6]
**What will you do?**
Write several passes over the Bril IR to transform it into LLVM-IR

**How will you do it?**
I will first start by writing a pass to transform Bril to SSA form. This will probably require extending the Bril AST with a PHI node. Then, from that representation I will output LLVM compatible code that can be compiled down to assembly and run natively on a machine. Also, if I end up doing this project in OCaml, I will need to create a parser and a node types for the Bril AST in OCaml.

**How will you empirically measure success?**
I will write a few test programs in typescript, compile them to Bril, then compile to LLVM, and finally to x86 assembly. I will ensure that the LLVM output by my pass is valid and that when the programs run their output is equivalent to the typescript program.

**Comment by sampsyo** [comment]
Seems neat! But I actually recommend that you *don't* bother trying to SSA-form LLVM. Instead, just use LLVM `alloca` to create mutable stack space for each variable. Some built-in LLVM passes will be able to clean this up most of the time and create the SSA-form register code you're expecting. This will end up being a simpler implementation that gets what you want.

Needless to say, converting Bril to SSA is a global analysis pass, which is not something we've covered yet. It's not that difficult, of course, but it will be the focus of class in a week or so.

> I will need to create a parser and a node types for the Bril AST in OCaml.

Or you can just deal with it in an untyped, JSON-y way. :smiley: But a more strongly typed OCaml AST library would be a cool side effect!
