### ISSUE TITLE
Project 2 Proposal: Partial Redundancy Elimination

### ISSUE THREAD

**Issue by Neroysq** [sampsyo/cs6120#60]
**What will you do?**
I will implement a partial redundancy elimination pass. The goal is to eliminate expressions that are redundant on some but not necessarily all paths through a program.

**How will you do it?**
I found [this slides](http://www.cs.cmu.edu/afs/cs/academic/class/15745-s12/public/lectures/L10-PRE-1up.pdf) helpful, and it also lists a list of references.

The algorithm roughly contains:
* find partially available expressions.
* for each such expression, check if safety(doesn't change program behavior) and performance(doesn't add new computations) are guaranteed after we make this expression fully available. If so then we can make it fully available and eliminate it.

There are more details about how to implement this algorithm in the slides.

**How will you empirically measure success?**
To make sure my implementation is correct, I will create test cases to check:
* no non-safe expressions are eliminated, such as insertions that can cause an exception.
* no expressions are eliminated by introducing new computations in any path.
* the result after this optimization matches the original.

For the performance part, I will measure static instruction count change and wall-clock time speedup using test cases. I am also wondering if I can measure the numbers of instructions in the execution traces because it seems we don't have an existing tool.

I expect the instruction count to increase because of computation insertions. But there should be significant wall-clock time speedup.

**Team members:**
Just me.

**Comment by sampsyo** [comment]
Sounds fantastic! Good luck.

If you have extra time, you might consider implementing the speculative version—i.e., one that can preemptively compute things, sometimes, even if it's not a guarantee that the results will be used. It could help in some circumstances.
