### ISSUE TITLE
Project 2 Proposal: Loop Unswitching

### ISSUE THREAD

**Issue by sameerlal** [sampsyo/cs6120#61]
**What will you do?**
Implement the loop unswitching optimization as described  
[on this wiki](https://en.wikipedia.org/wiki/Loop_unswitching).    I will implement this using adaptive software development principles so it can be easily extended to include other loop optimizations.

**How will you do it?**
I will first create a for loop abstraction that can be used in the SSA intermediate form.  I will then follow the algorithm described in [this paper](https://www.cs.rit.edu/~mtf/student-resources/20155_surawski_mscourse.pdf).  The majority of my effort will be in finding conditional branch blocks on invariant values within a loop's body.  I may make slight modifications to allow for multiple nested loops and conditions (nested conditionals that are independent of their parent loop may need not to be unswitched). 

Relevant link:  http://www.ucw.cz/~hubicka/papers/proj/node10.html

**How will you empirically measure success?**
To measure success, I will email the authors in the aforementioned paper to acquire their testing benchmark (no response).  Most empirical success is based off of the success of this project.  Since unswitching allows for the possibility of separate loop optimizations, implementing this allows other optimizers to optimize components that may never be hit.  Another way to test this, as it has been pointed out, is to count the number of branches.

Edited with suggestions from below

**Team members:**
Solo

**Comment by sampsyo** [comment]
Sounds great! Doing this in SSA form does seem like the right thing.

I don't think you necessarily need to use the original benchmarks, FWIW. It couldn't hurt, and I like the idea of emailing them, but it shouldn't be too hard to concoct small benchmarks that could meaningfully benefit from unswitching.

I don't think you need to worry too much about vectorization here. There is plenty of benefit to be had just from reducing the amount of branching. You might even consider measuring that directly as a way to get a more complete picture of your optimization's effects: what's the reduction in the number of branch instructions executed?
