### ISSUE TITLE
Project 2 Proposal: Stochastic Superoptimizer

### ISSUE THREAD

**Issue by splashofcrimson** [sampsyo/cs6120#62]
**What will you do?**
I will implement a minimal stochastic superoptimizer modeled after STOKE (http://stoke.stanford.edu/). The goal is to do a random search over alternate equivalent programs, and evaluate them per some cost metric to generate an optimized representation of the source code.

Inspiration: https://blog.acolyer.org/2017/03/30/stochastic-program-optimization/

**How will you do it?**
For simplicity, the source (STOKE) targets loop-free code, so I will do the same. My intended approach is as follows:
1. Build infrastructure to apply perturbations to the original program and generate a sample space of similar programs to explore/evaluate (remove, add, and adjust instructions).
2. Evaluate correctness of the new programs. The original STOKE paper uses a two-step process to validate equality of two x86 assembly sequences (The original program X and the perturbed program Y).
    - Assert that X and Y produce identical outputs given a series of live inputs. Since I might want to generate programs on the order of thousands in step one, this allows the superoptimizer to quickly disregard programs that are incorrect.
    - If X and Y produce identical outputs, pass X and Y to an SMT solver (Something like https://github.com/Z3Prover/z3) and verify that they are indeed the same.
3. Write a cost model to quantify the performance of each program (Wall clock time/Some other cost metrics)
4. Use an MCMC technique like the Metropolis-Hasting algorithm to select sample programs based on some approximate probability density function.
5. Output a list of programs and scores sorted in accordance with the cost model.

**How will you empirically measure success?**
Given a list of valid representations of the original program, I will take the best 5 - 10 and use them as a basis for my evaluation. There should already be a theoretical guarantee of correctness, so I will focus primarily on performance.

I will put together a test suite of loop-free programs to run through the superoptimizer. The output code sequences will then be evaluated against two metrics: static instruction count and actual execution time of the Bril IR on the interpreter. I can do a similar evaluation on both the original Bril program and a Bril program optimized using more traditional techniques (DCE, Copy prop, Const fold, etc.). The cost model itself will have a large effect on how optimal programs are selected, so a cool stretch goal would be to test a few different cost metrics and evaluate the results.

As an extra sort of evaluation, I'm really curious to see if the superoptimizer is capable of uncovering these more 'traditional' optimizations through random search. I'll do a more qualitative sweep of the programs that are output and see what techniques it manages to discover!

**Team members:**
Myself!

**Comment by Chillee** [comment]
I actually have quite a bit of thoughts on this paper, and have played around a bit with extending it before, so here are some of my unsolicited opinions. I haven't looked too closely in some time, so some of the details might not be exactly right.

Overall, I think it's an interesting approach. However, there's a couple of things I initially thought were interesting about the work that didn't end up being interesting (imo).

1. The use of MCMC. I think they're using MCMC only in the most technical of terms. I wasn't particularly convinced that the "moves" they could make at each step were well-defined, and their estimation of the distribution was also suspicious. 

They also use the uniform distribution to sample their moves. A follow up work actually learns the distribution, but their results are not particularly convincing to me. Specifically, the vast majority of their performance comes from learning fixed weights. 

2. If you take a look at their results, they're less impressive than they may first appear. The vast majority of their results are roughly equivalent to GCC/ICC, and I suspect their improvements primarily come from essentially randomly fuzzing their assembly until it resembles the -O3 versions. In addition, of their few results where they substantially outperform GCC/ICC, one of them was simply using the `popcnt` instruction, another was using some vectorized instruction, and both were optimizations that GCC/ICC did today (which is not a knock to the original paper). The main "algorithmically different" optimization they did that I thought was interesting was the montgomery multiplication one, and I had some issues reproducing that (with their code).

3. Working with their code is actually really difficult. I had repeated issues with crashes/memory leaks/segfaults. Integrating with the SMT solver in particular is something I expect you to have issues with.

Essentially, reproducing this paper for a whole new language is a difficult endeavor, and may be more difficult than you expect.

If you're interested, I can talk some more about my thoughts on this paper in person.

**Comment by splashofcrimson** [comment]
Hey, thanks for your feedback! I agree that reproducing the paper for Bril will be difficult (especially integrating with an SMT solver - this is what I'm most worried about). That being said, I argue this project will still have some interesting results, even if they were already produced in the original paper.

1. Given that I'm reproducing the paper myself by hand, albeit as barebones as possible, I should be able to largely avoid their buggy codebase. Also, I'm planning to focus on sequences of simple instructions (assignment/basic operations), while the original paper targets the x86 instruction set, so I expect the sample space to be more manageable.

2. To be honest, I don't expect my results to be superior or even comparable to a series of traditional optimization passes. What I am most curious about, however, is STOKE's ability to perform these optimizations without explicit instruction. Can it perform DCE, CSE, etc. by sparsely sampling a large program space? Granted, I should (and will) do an exhaustive quantitative analysis of performance (perhaps static instruction count/code size would be an 'easier' metric to compare upon).

If my results after running some experiments on STOKE are similar to what you've brought up I wouldn't be very surprised. While looking around I found some other superoptimizers that might be promising, such as [souper](https://github.com/google/souper), which targets the LLVM IR itself.

I'm interested to see what Professor Sampson's opinions are. Also, I'd love to talk sometime before class tomorrow if you have more thoughts!

**Comment by sampsyo** [comment]
Cool! This is, at the very least, quite ambitious. To be blunt, I think you're not very likely to be able to get awesome results on realistic code—successfully getting good results in STOKE required:

- Very high test execution throughput.
- Sensitive hyper-parameter tuning (e.g., selecting the transition function).
- Carefully selected benchmarks.

All of which are pretty hard to come by (except maybe the last one, because you can just steal their benchmarks?). So I just want to prepare you for some amount of disappointment. Your project can still be "successful" in the sense that you evaluate it convincingly and write about it well while learning something important! But the actual results might look negative.

One thing I'm a little worried about in terms of effort is that you have to have a verifier. That's kind of a while project in itself—in fact, [it was a Project 1](https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/a-verification-backend/). Maybe you can reuse Shrimp instead of writing your own.

**Comment by splashofcrimson** [comment]
I'll keep the words of caution in mind - thank you for the feedback!
