### ISSUE TITLE
Project 2 Proposal: Register Allocation

### ISSUE THREAD

**Issue by 0x486F626F** [sampsyo/cs6120#65]
**What will you do?**
Processors usually have some spare registers which can be used to store variables for faster access. We are going to implement a register allocation algorithm for Bril via graph coloring.

**How will you do it?**
For a function we will do:
1. Liveness analysis: create a graph with nodes representing live ranges of variables and edges representing interference between live ranges. 
2. Graph K-coloring: find a K colorable subgraph of the graph above, where the K is the number of available registers.
3. We assign the K registers to the K colored nodes and spill uncolored nodes in memory.

We will use special variable names in Bril to represent registers, like `__r0` ~ `__r63`, so that we can generate a Bril code with register allocated. 

**How will you empirically measure success?**
We will modify the brili to count the number of implicit memory access operations for those data not in registers. For example:
* `a: int = const 2` has 1 memory access operations (store a)
* `a: int = id b` has 2 memory access operations (load b, store a)
* `c:int = add a b;` has 3 memory access operations (load a, load b, store c)

Accessing register values (the special variables above) will not be counted as a memory access:
* `__r1: int = const 2` has 0 memory access operations
* `a: int = id __r2` has 1 memory access operations (store a)
* `c:int = add a __r2;` has 2 memory access operations (load a, store c)

We will compare the total number of memory access operations for the same program with and without register allocation.

If we have time, we also want to extend the Arm 64 Assembly translator #43 to support register allocation,
and test it on a "real" machine.

**Team members:**
@xu3kev

**Comment by sampsyo** [comment]
This sounds great! Thanks for the detailed plan about how you'll measure "memory reads" with your concept of "registers" in Bril.

FWIW, I think it's totally fine if you don't get around to doing register allocation for real machine registers, i.e., improving the Arm backend. Doing this just in the comfort of Bril itself will be fine. But that of course would be extra cool.

See also #68, which is also proposing to do register allocation.
