### ISSUE TITLE
Project 2 Proposal: Local Value Numbering Optimizations for Cril

### ISSUE THREAD

**Issue by Bhargee** [sampsyo/cs6120#66]
**What will you do?**
We will implement common subexpression elimination, copy propagation, constant folding, and constant propagation for cril, the C Bril interpreter. 
**How will you do it?**
First, we will change the core of cril to operate on basic blocks. Then we will implement local value numbering. Once that is done, we will implement each of the above optimizations. 
**How will you empirically measure success?**
We will enrich the set of cril benchmark programs with more matrix multiplication and polynomial multiplication programs (n=10,25,50,100). Then we will benchmark the performance of unmodified cril, and do the same with the optimizations implemented. 
**Team members:**
@epeguero

**Comment by sampsyo** [comment]
Hi, @Bhargee—can you please talk to me about this in person? I think we may have miscommunicated about the scope of Project 2.

The idea in Project 2 is to implement an optimization: that is, something that takes in a Bril program and outputs a new Bril program that does the same thing, only faster.

Critically, I don't know what it means to implement copy propagation "for Cril." A good implementation of copy propagation doesn't care what interpreter it's running on. It just optimizes Bril programs.

**Comment by sampsyo** [comment]
To revise your proposal here: you're going to implement GVN, much like #59. Then, you plan to evaluate the speedup using your interpreter, right?

One other thing, about your benchmarks:

> We will enrich the set of cril benchmark programs with more matrix multiplication and polynomial multiplication programs (n=10,25,50,100). 

Please strive to make your benchmarks more diverse. Just focusing on different problem sizes for the same tasks won't teach you much about how well your optimization is working.
