### ISSUE TITLE
Project 2 Proposal: Probabril and Abstract Intervals

### ISSUE THREAD

**Issue by orichardson** [sampsyo/cs6120#67]
**What will you do?**
We intend to integrate [probabilistic bril](https://github.com/sampsyo/cs6120/issues/20) with its [floating point extension](https://github.com/sampsyo/cs6120/pull/48) and implement an optimizing pass on the states generated by this algorithm.  At the moment, probabilistic bril keeps track of every attainable combination of environment and location in the program; this makes branching integer computations problematic, and real-valued random variables impossible. In order to compactly represent distributions with infinite support, we need a finite partition of the state space into classes that have the same control flow --- for floats, we can get some of this with abstract intervals.

**How will you do it?**
We will start by adding a continuous bounded `rand` instruction to bril, which is interpreted in the regular interpreter (`brili`) as javascript random, and in the exact abstract interpreter (`xbrili`) as an interval. Comparisons such as `lt` and `ge` split intervals; operations such as addition and multiplication track the end points of intervals.

The mass distribution within the interval can be represented as a polynomial for any finite combination of operations. We will not be able to represent fixed points of these distributions in the presence of arbitrary control flow, but we can still iteratively compute a Taylor approximation, and possibly exactly solve for some of the moments.

By representing program state in this way, we enable the following optimizations:

- dramatic reduction of state space in the exact solver
- dead code elimination by pruning branches with tests out of range
- elimination of redundant operations to construct distributions

For example, the following code
```
{
  five : float = const 5f;
  one : float = const 1f;
retry:
  x : float = rand ; 
  x : float = fmul x five; 
  test : bool = gt x one;
  br test retry finish;
finish:
  ret;
}
```

can be reduced to this:
```
{
  four : float = const 4f;
  one : float = const 1f;
  x : float = rand ; 
  x : float = fmul x four; 
  x : float = fadd x one;
  ret;
}
```
... by simply computing the limit point of the transformer at the branch to be the interval `[1,4]` and re-expanding.

**How will you empirically measure success?**
We will evaluate correctness on small test programs which generate distributions of floating-point values, and exhibit particular characteristics of interest that we would like to deal with. These snippets will include some basic arithmetic operations and control flow, demonstrating that our algorithm can reason correctly about the features we expect to see in realistic programs.  We will then use the random instruction generation utility from probabril to verify that samples from the interpreter are consistent with the results of the abstract interpreter.

After having tested for correctness, we will investigate performance on larger programs, with and without each optimization pass.  For this analysis, we will compare against some hand-crafted programs of ~50-100 lines of code with more complicated control flow, and, time permitting, a restricted subset of scaling random ones (in particular, those without multiplications in unbounded loops).

**Team members:**
@Checkmate50 @orichardson

**Comment by sampsyo** [comment]
OK, this sounds intriguing! I think I need a little detail about a couple of things here, though. What does this mean?

> The mass distribution within the interval can be represented as a polynomial for any finite combination of operations.

I don't quite understand how you're going to represent distributions using polynomials. Are you literally using polynomial coefficients from a Taylor expansion? What happens if you add U(0.0, 1.0) with U(3.0, 5.0)? Is that also a polynomial? 

Or maybe you don't mean a polynomial in the way I'm thinking of it?

I also want to encourage you to focus on getting a minimal, working, boring thing done first **before trying to do anything fancy**. That means using an obvious, general representation for continuous, finite-support values that consist of sums of uniform distributions—and a way to use that to produce "foregone conclusions" from instructions like `lt`. Then you'll need a global CFG-based DCE pass to eliminate unnecessary branches! (Please don't forget about that part as part of your minimum viable product.) Get that working quickly and only then layer more stuff on top of that.

**Comment by orichardson** [comment]
U[0, 1] + U[3, 5] = U[3, 6], so long as the two variables are independent (the cdf of which is a degree 1 polynomial). What I originally had in mind was tracking the density in with polynomials of one variable, which is equivalent to just choosing some canonical internal points (i.e., degree - 1) on the interval and specifying the relative density there.

On the other hand, if they are dependent, e.g., `z` in the example below, 

```
x = rand; 
y = 1 - x; 
z = x + y;
```

then this is not true, and so actually will need to keep track of the underlying random variables; we can still use polynomials for this, but now we need to label the variables: interpret y as [[y]] = 1-x, and [[z]] = [[x]] + [[y]] = x + 1-x = 1. When a variable goes out of scope, we can squash the variable to its density (as in the uncorrelated case), so that loops do not accumulate an infinite number of variables.

**Comment by sampsyo** [comment]
OK, sounds good!
