### ISSUE TITLE
Project 2 Proposal: Register allocation via graph coloring

### ISSUE THREAD

**Issue by sa2257** [sampsyo/cs6120#68]
**What will you do?**

We propose to add register allocation to `bril` and evaluate how graph coloring can improve performance compared to a naïve allocation.
We'll implement register allocation on an extension of `bril` that can be simulated as assembly code on an extended `brili`.

**How will you do it?**

We will assume variables used in `bril` to be registers and treat `bril` as assembly code. 
We will map `bril` variables to a fixed number of register names, add `load` and `store` instructions and memory addresses to `bril` (we will consider the possibility to use https://github.com/sampsyo/bril/pull/10) and use them to spill excess variables to memory.
Then we will implement graph coloring based register allocation which includes generating an interference graph, graph coloring and register coalescing.

**How will you empirically measure success?**

We will use a simulator that behaves similar to `brili` but will also count the number of load and store instructions. We will use a baseline which will use a naïve strategy to do register allocation. Measure of success will be a comparison in the simulator between this baseline and graph coloring based implementation on, 
- Overall instruction count
- Total number of loads and stores 

**Team members:**

@hcp922, @sa2257 and @qtt2 (audit)

**Comment by sampsyo** [comment]
Sounds great! See also #65, which has a different evaluation proposal where registers are just variables with special names (and other, non-special variables are imagined to be on the stack). You might consider collaborating on the representation or sharing an instrumented interpreter.
