### ISSUE TITLE
Project 1 Proposal: Integer SIMD support

### ISSUE THREAD

**Issue by pbb59** [sampsyo/cs6120#7]
I plan to add bril support for SIMD instructions and simple auto-vectorization in the Typescript frontend.

I'll modify the brili interpreter to support vector types in addition to int types. Vector instructions will be executed using Typescript's vectorization support. To support auto-verctorizaton, I will modify ts2bril. When a loop is encountered, it will need to be partially unrolled and SIMD bril instructions must be emitted.

I expect slight program speedups due to the use of vector instructions (assuming there are enough loop iterations!).

**Comment by sampsyo** [comment]
Nice! Will the vector types be fixed-width or variable-width?

> Typescript's vectorization support

I wasn't aware this was a thing and couldn't find anything about it in a quick google session… got a link?
