### ISSUE TITLE
Project 2 Proposal: Value-Range Analysis

### ISSUE THREAD

**Issue by enterprisey** [sampsyo/cs6120#72]
**What will you do?**
Implement [value range analysis](https://en.wikipedia.org/wiki/Value_range_analysis) for Bril, as described in [Harrison 1977](https://ieeexplore.ieee.org/document/1702432) and [Birch et al 2004](http://www.cs.fsu.edu/~engelen/cpcpaper.pdf). This pass will attempt to determine bounds on variables and statically evaluate comparison instructions based on the results.

**How will you do it?**
I will follow the procedure outlined by Harrison, creating a data flow graph and propagating interval information along it. I will then elide comparison instructions. After that part works, I will implement the Birch et al. algorithm, which is more pointer-specific.

**How will you empirically measure success?**
I will write a number of benchmarks that make heavy use of pointers, arrays, and interval checks. I may have to write a frontend for a language that has pointers and arrays, probably for a small subset of C. I will measure how many instructions I am able to eliminate with this pass. I will also test the pass on more programs found "in the wild", as I am likely to write benchmarks that include more arrays and pointers than would normally be seen in an "average" program.

**Team members:** Just me.
[@mention their GitHub usernames, if it's not just you]

**Comment by sampsyo** [comment]
OK, sounds good! But can you clarify two things, please?

- Why do you need to use an extension with pointers & arrays? It seems like this would work on ordinary integer programs without pointers. Perhaps you think the main benefit is to be gotten from eliminating bounds checks?
- If you do use pointers/arrays, which extension will you adopt?

**Comment by enterprisey** [comment]
* Yes, bounds checks would be one important aspect of this. The Birch et al paper also talks about array and pointer optimizations, so I would like to implement those.
* I will use the Zagieboylo/Doenges "manually managed memory" extension.

**Comment by sampsyo** [comment]
OK, sounds good—but what I was sort of getting at with my first question is that I don't yet understand what "array and pointer optimizations" would be _other than_ bounds checks. Is there some other canonical example?

**Comment by enterprisey** [comment]
There don't seem to be any other important optimizations that range analysis enables specifically for arrays and pointers. People really like writing about bounds checks, apparently. I found some other more general applications, though. Integer overflow checking is the big one, as well as range-aware register allocation, parallelization analysis (i.e. side-effect analysis for array accesses in loops), and static branch prediction (probably not very relevant to bril, though).

**Comment by sampsyo** [comment]
Sounds good. Bounds checking by itself is of course a big deal because bounds checks are so pervasive in safe code. Just wanted to check whether there was anything I was missing.
