### ISSUE TITLE
Project 1 Proposal: Making function calls work

### ISSUE THREAD

**Issue by Blue9** [sampsyo/cs6120#8]
**What will you do?**
We will make function calls work. Also, we'd like to explore the idea of adding function parameters, anonymous functions, and partial function applications.

**How will you do it?**
We will first add a call keyword to the language and add a call instruction to the IR spec. Then, we will modify the interpreter to handle function calls.

**How will you empirically measure success?**
We will measure our success by testing various functions and verifying that their outputs are expected. We will also test deep recursion to benchmark the interpreter's performance.

With @splashofcrimson and @sameerlal

**Comment by sampsyo** [comment]
Sounds good! If I can make one recommendation for how this should work: I think `main` should be allowed to have parameters. Then, the interpreter could provide arguments directly to `main` to enable more interesting computations on unknown inputs (without parsing argv, as C programs must do).

> Also, we'd like to explore the idea of adding function parameters, anonymous functions, and partial function applications.

While this sounds interesting, please focus on the first-order version of functions up front. The design seems clear, and compilation to assembly-like targets shouldn't be too hard. To add higher-order functions, we'll make backends quite a bit more complicated. So perhaps we'd need two versions of the IR: one with higher-order functions and one without, with a provided transformation to lower from one to the other.
