### ISSUE TITLE
Project 1 Proposal: Generate ARM64 assembly from Bril

### ISSUE THREAD

**Issue by 0x486F626F** [sampsyo/cs6120#9]
**What will you do?**
Write a code generation program that takes a JSON representation of a Bril program and generates aarch64 assembly code. The generated assembly code should be able to run on aarch64 processor, such as Raspberry Pi 3 (or later versions, which have 64 bit ARM processor)

**How will you do it?**
The code generation program should not only support current Bril instructions, but it also should be easy to expand for more features, such as interesting features implemented by other teams.
Therefore, I will first build a AST from JSON Bril, then generate assembly code for each operations. Most of current Bril operation are easy to do, there are almost one-to-one translations between Bril and ARM assembly. The only relatively tricky part is print, which could be solved by calling printf from C.

**How will you empirically measure success?**
1. Build a benchmark set of different types of workload
2. Comparing the performance between ARM64 binary and brili (maybe and some interpreter or binaries from other team) on a Raspberry Pi 3B+ board.

**Comment by sampsyo** [comment]
Hi, Hongbo! This sounds interesting but I have to warn you that this project sounds like a lot of work. This project is meant to be sort of self contained, and I worry a little that you might spend lots of time wrangling with assembly details to make this work. Namely, you'll either have to do register allocation or generate code to load and store variables from the stack. And to be able to run programs, you'll also have to figure out a way to link the code you generate with a C-like entry point `main` and possibly libc to generate a complete executable.

Anyway, I won't stop you from attempting this, but you might consider narrowing the scope somewhat to make sure you can accomplish something complete.

>  I will first build a AST from JSON Bril

To clarify, this is almost a no-op. You don't need to do anything to build the AST—just parse the JSON.

> The generated assembly code should be able to run on aarch64 processor, such as Raspberry Pi 3 (or later versions, which have 64 bit ARM processor)

Indeed, the Raspberry Pi 3's processor is an ARMv7 machine, so AFAIK won't run AArch64 code.

**Comment by 0x486F626F** [comment]
Hi Adrian, Thanks for the feedback! I wrote a very hacky Python code that does the code generation. 

> Namely, you'll either have to do register allocation or generate code to load and store variables from the stack.

Currently, I have a symbol table that maps variable name to a offset on stack from frame pointer ($29). 

> you'll also have to figure out a way to link the code you generate with a C-like entry point main and possibly libc to generate a complete executable.

For now I just do `gcc 1.s` and let gcc to do everything else for me, a little bit cheating :p 

> Raspberry Pi 3's processor is an ARMv7 machine, so AFAIK won't run AArch64 code.

RPi 3B+ actually has a ARMv8 processor. Although the official Raspbian is 32-bit, using a 64-bit system like Ubuntu will support aarch64.
