### ISSUE TITLE
Project 3 Proposal: Run-time execution profiling

### ISSUE THREAD

**Issue by neiladit** [sampsyo/cs6120#97]
**What will you do?**
We are planning to collect run-time information including number of LLVM instructions, basic blocks and memory instructions being executed. We can also look into expensive instructions like multiplication and branches. We also propose to count the number of times each function is called.

**How will you do it?**
Profiling at run-time can be tricky due to change in control flow, hence LLVM compiler cannot tell the dynamic behavior at compilation time. We can however, do a basic block analysis where we have a single entry and exit point implying that the instructions within a basic block will execute. In order to collect run-time statistics, we can introduce a profiling function in each basic block of the IR code using IRBuilder. The profiling function will modify global variables (counters for the statistics being measured) atomically to ensure well defined behavior even in multi-threaded applications.

**How will you empirically measure success?**
One idea could be to profile benchmarks with and without optimization directives like o3. We would expect optimized benchmarks to have less LLVM instructions or less expensive operations than the unoptimized version.
Another thing to do would be to run standard c based profilers like gprof which gives us the number of times a function is called and compare it with our output.

**Team members:**
@elainejiang @tissue3

**Comment by sampsyo** [comment]
Sounds great! This shouldn't be too hard, I think. I was going to ask about your plan for parallel programs, but it sounds like you've worked that out—just use atomic ops on those global counters. :smiley:
